/*
 Quantcast measurement tag
 Copyright (c) 2008-2017, Quantcast Corp.
*/
window.__qc=function(a){if(a.__qc)return a.__qc;var p=a.document,y=a.navigator,F="4dcfa7079941 127fdf7967f31 588ab9292a3f 32f92b0727e5 22f9aa38dfd3 a4abfe8f3e04 18b66bc1325c 958e70ea2f28 bdbf0cb4bbb 65118a0d557 40a1d9db1864 18ae3d985046 3b26460f55d".split(" "),c=!1,e=0,m=[],M=[],z=[],x={tcYgbCswcTSeq:1,"01-0VIaSjnOLg":1,aD1qr93XuF6aC:1,"56WJ0KtIxWJ_2":1,T1nhLcmCjVzQS:1,zddNYNtUkUhdQ:1,"59TntzuqummDw":1,P7x87XHnVfbWr:1,HGAVM7nQJ_sep:1,"w9vzus-GKCA0U":1,"00TsOkvHvnsZU":1,effSsmMYCbAck:1,PFW5FesqXn206:1,
"0dYLvhSGGqUWo":1,c1rF4kxgLUzNc:1,"5brKQLtleyIQU":1,"mEzuYq24VEJ-3":1,"57OGVHgSOoedo":1,"e7wR0qsM6-pDa":1,"8tgFhCTDYhV2V":1,"82MbSinIaQJw2":1,buQ2dAnrdTGCS:1,"49SVsgIZlUqPk":1,eeFYJkotb1rUU:1,EzVU5HfAMVqEV:1,"45nh8QKbsf2Xk":1,sLJ2v5QaN4z2Y:1,"5cvC4NOeGmtNA":1,"573scDfDoUH6o":1,"915Y6SMHQQJHI":1,z0zMG4nCgXzzj:1,"124BfeS-bwiSE":1,"ZzStSGgW6hG-4":1,KUMT4fYgcdEeg:1,d9vfr8QTWnv1E:1,fug7wP0GuN1h6:1,cd12aNCzw_ZaB:1,"51zXP5Cc9sxvQ":1,"4dIM5nVs2rFio":1,"8fZNjMQsH1Ews":1,C6W3aFrWFMS7m:1,N7ekbgK3G3jrt:1,dfQGRefil9mes:1,
"9axVJDmh4EHIM":1,NPcfSf1E0V1T1:1,"72V4-XKpaKDrE":1,"8cV3w6ZJH0sXI":1,sHwqAaPHqVjee:1,b15U9CAASyBMc:1},t=[],A={},G=0,H=[],D=null,W={},w={},ha=null,u,X=[].slice,ia,Y,N,k,B,Z,O,ja,ka,la,I,$,P,Q,ma,J,na,oa,pa,qa,q,ra,C,R,sa,aa,ta,ua,ba,s,va,ca,S,T,wa,xa,U,ya,da,ea,za,fa,E,K,L,V,ga,v=function(b){try{return{init:Q,hash:P,rules:wa,hasRules:U,defaults:za,__qc:function(){return!0}}[b].apply(null,X.call(arguments,1))}catch(d){return!1}};v.evts=0;v.v=2;v.SD=F;v.qpixelsent=[];T=function(b){var d=b?b.length||
0:0,a;for(a=0;a<d;a++)if(!b[a])return!1;return!0};ea=function(b){(b=b||a._qacct)&&(ba(t,b)||t.push(b))};ba=function(b,d){var a=b.length,f;for(f=0;f<a;f++)if(b[f]===d)return!0;return!1};ca=function(b){return{}.toString.call(b).match(/\s([a-zA-Z]+)/)[1].toLowerCase()};S=function(b){var d,a;d=ca(b);if("array"===d)return b.slice(0);if("object"===d){d={};for(a in b)b.hasOwnProperty(a)&&(d[a]=b[a]);return d}return"string"===d?""+b:b};U=function(b){return ba(z,b)};za=function(b,d){var a;b&&((a=W[b])&&(d=
V(d,a)),d.qacct&&delete d.qacct,W[b]=d)};fa=function(b){var d,g;if(k(b))for(d in b)if("string"==typeof b[d]){d=b.event||"load";g=b.media||"webpage";"rule"!==d&&"load"!==d||"webpage"!==g&&"ad"!==g?q(b):(g=b.qacct||a._qacct,b.qacct=g,d=(d=w[g])?V(d,b):b,w[g]=d);ea(b.qacct);break}else"object"==typeof b[d]&&null!=b[d]&&fa(b[d])};V=function(b,d){var a={};a.qacct=b.qacct||d.qacct;a.event="load"===b.event||"load"===d.event?"load":b.event&&d.event?b.event||d.event:null;a.media=null;a.media="webpage"===b.media||
"webpage"===d.media?"webpage":"ad"===b.media||"ad"===d.media?"ad":b.media||d.media;aa(a,b,d);aa(a,d,b);a.event||delete a.event;a.media||delete a.media;return a};aa=function(b,d,a){var f,e,c,r,m,l;for(f in d)d.hasOwnProperty(f)&&!b.hasOwnProperty(f)&&(e=d[f],c=a[f],r="",m=!!e&&"string"==typeof e,l=!!c&&"string"==typeof c,m&&(r=e),m&&l&&(r+=","),l&&(r+=c),b[f]=r)};E=function(){var b=[],d,a;if(!(0<G)){va();for(d in w)w.hasOwnProperty(d)&&w[d]&&(a=w[d],b.push(a),delete w[d]);1==b.length&&q(b[0]);1<b.length&&
q(b)}};K=function(b){var d=[],a,f;for(a=0;a<b.length;a++)f=b[a],x.hasOwnProperty(f.substring(2))?A[f]=5:U(f)||d.push(f);if(0===d.length)E();else for(a=0;a<d.length;a++)f=d[a],z.push(f),ta(f)};ua=function(){for(var b;H[0]&&("loaded"==H[0].readyState||"complete"==H[0].readyState);)b=H.shift(),b.onreadystatechange=null,D.parentNode.insertBefore(b,D),L()};ta=function(b){var a,g;a=("https:"===p.location.protocol?"https://":"http://")+"rules.quantcount.com/rules-"+b+".js";D=D||p.scripts[0];G++;g=p.createElement("script");
"async"in g?(g.src=a,g.async=!1,g.onload=function(){A[b]=0;L()},g.onerror=function(){A[b]=1;L()},D.parentNode.insertBefore(g,D)):g.readyState?(A[b]=2,H.push(g),g.onreadystatechange=ua,g.src=a):(A[b]=4,L())};L=function(){G-=0<G?1:0;E()};wa=function(){var b=!0,a,g,f;if(arguments.length){f=function(a){b?fa(a):q(a,!0)};for(a=0;a<arguments.length;a++)g=X.call(arguments[a],0),g.splice(1,0,f),xa.apply(null,g);b=!1;c&&E()}};xa=function(b,a){var g=[],f=[],e=a||q,c,r,m,l,n;if((c=X.call(arguments,2))&&c.length){r=
c[0]||T;m=c[1];l=c[2];c=l.length;for(n=0;n<c;n++)g.push(!1),f.push(null);g={p:b,f:g,r:r,c:l,a:m,v:f};U(b)||z.push(b);M.push(g);ya(g,e)}};ya=function(b,a){var g=b?b.c?b.c.length:0:0,f;for(f=0;f<g;f++)(function(f){var g,c;try{g=b.c[f][0],c=b.c[f].slice(1),c.splice(0,0,function(g){b.f[f]=!0;b.v[f]=g;da(b,a)}),g.apply(null,c)}catch(e){b.f[f]=!0,b.v[f]=!1,da(b,a)}})(f)};da=function(b,a){var g=b.a,f=b.v,c=b.r||T,e,m,k,l,n,h;(e=T(b.f))&&(e=e&&c(f));if(e)for(f=0;f<g.length;f++)try{m=g[f][0];k=1<g[f].length?
g[f].slice(1):[];k=k.concat(b.v);l=m.apply(null,k);n={qacct:b.p,event:"rule"};for(h in l)l.hasOwnProperty(h)&&"qacct"!==h&&(n[h]=l[h]);a(n)}catch(p){}};ia=function(){return Y(0)!==Y(6)?1:0};Y=function(b){b=new Date(2E3,b,1,0,0,0,0);var a=b.toGMTString(),a=new Date(a.substring(0,a.lastIndexOf(" ")-1));return b-a};N=function(b){return b.replace(/\./g,"%2E").replace(/,/g,"%2C")};B="function"===typeof encodeURIComponent?encodeURIComponent:N;k=function(b){return"undefined"!=typeof b&&null!=b};Z=function(){return Math.round(2147483647*
Math.random())};O=function(b){var a="",g=p.cookie,f;if(!g)return a;f=g.indexOf(b+"\x3d");b=f+b.length+1;-1<f&&(a=g.indexOf(";",b),0>a&&(a=g.length),a=g.substring(b,a));return a};ja=function(){var b="",a=I(),g,f,c;if(1===e)return";fpan\x3du;fpa\x3d";g=P(a);for(f=0;f<F.length;f++)if(F[f]===g)return";fpan\x3du;fpa\x3d";g=new Date;f=O("__qca");if(0<f.length){try{c=+f.split("-")[2],338688E5<g-c&&(p.cookie=["__qca\x3d",f,"; expires\x3d",(new Date(c+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",a].join(""))}catch(m){}b+=
";fpan\x3d0;fpa\x3d"+f}0===O("__qca").length&&(f="P0-"+Z()+"-"+g.getTime(),p.cookie=["__qca\x3d",f,"; expires\x3d",(new Date(g.getTime()+338688E5)).toGMTString(),"; path\x3d/; domain\x3d",a].join(""),f=O("__qca"),b=0<f.length?b+(";fpan\x3d1;fpa\x3d"+f):b+";fpan\x3du;fpa\x3d");return b};ka=function(b){p.cookie=b+"\x3d; expires\x3dThu, 01 Jan 1970 00:00:01 GMT; path\x3d/; domain\x3d"+I()};I=function(){var b,a,g,f;b=p.domain;"www."===b.substring(0,4)&&(b=b.substring(4,b.length));a=b.split(".");f=a.length;
if(3>f)return b;g=a[f-1];return 3>g.length?b:b=a[f-2]+"."+g};$=function(b,a){var g;for(g=0;g<a.length;g++)b^=a.charCodeAt(g),b+=(b<<1)+(b<<4)+(b<<7)+(b<<8)+(b<<24);return b};P=function(b){var a;a=$(2166136261,b);b=$(3386659096,b);return Math.round(Math.abs(a*b)/65536).toString(16)};R=function(b,d,g){var f="",c=a._qacct,m=null,r="webpage",p="load",l={},n,h,c=d?d.qacct||a._qacct:a._qacct;n=w[c];d?n&&(d=V(d,n)):d=n;c&&delete w[c];if(null!=d)for(h in d)l[h]=!0,d.hasOwnProperty(h)&&"string"===typeof h&&
"string"===typeof d[h]&&("uid"===h||"uh"===h?(ma()||(m=P(d[h])),delete d[h]):"qacct"!==h&&(0<d[h].length?f+=";"+h+b+"\x3d"+B(d[h]):l[h]=!1,"media"===h&&(r=d[h]),"event"===h&&(p=d[h])));if("string"!==typeof c){if(!k(a._qacct)||0===a._qacct.length)return"";c=a._qacct}if(c&&(n=W[c]))for(h in n)"string"===typeof h&&n.hasOwnProperty(h)&&!l[h]&&(f+=";"+h+b+"\x3d"+B(n[h]),"media"===h&&(r=n[h]),"event"===h&&(p=n[h]));l=A[c];k(l)||(l=3);f+=";rf"+b+"\x3d"+l;"string"===typeof m&&(d.uh=m,f+=";uh"+b+"\x3d"+B(m));
if("webpage"===r&&"load"===p){for(d=0;d<v.qpixelsent.length;d++)if(v.qpixelsent[d]===c&&!g)return"";v.qpixelsent.push(c)}"ad"===r&&(e=1);return";a"+b+"\x3d"+c+f};sa=function(){var b=p.getElementsByTagName("meta"),a="",c,f,e,m;for(c=0;c<b.length;c++){e=b[c];if(1E3<=a.length)return a;k(e)&&k(e.attributes)&&k(e.attributes.property)&&k(e.attributes.property.value)&&k(e.content)&&(f=e.attributes.property.value,e=e.content,3<f.length&&"og:"===f.substring(0,3)&&(0<a.length&&(a+=","),m=80<e.length?80:e.length,
a+=N(f.substring(3,f.length))+"."+N(e.substring(0,m))))}return B(a)};la=function(a){return"object"===typeof a?["p","approved"===a.consent?"a":"d","asserted"===a.source?"e":"i"].join(""):""};ma=function(){var b=!1;k(a.external)&&(b=a.external,b="function"===typeof b.InPrivateFilteringEnabled&&!0===b.InPrivateFilteringEnabled());return b||"1"==y.doNotTrack||"yes"===y.doNotTrack||"1"==y.msDoNotTrack};q=function(b,d){var c="function"===typeof encodeURIComponent?"n":"s",f=Z(),M="",z="",r="",t="",l="",
n="u",h="1",s=0,u=[],q,w,x,A;e=0;k(v.qpixelsent)||(v.qpixelsent=[]);if(k(b))for(q in b)if("string"==typeof b[q]){z=R("",b,d);break}else"object"==typeof b[q]&&null!=b[q]&&(++s,z+=R("."+s,b[q],d));else"string"===typeof _qacct&&(z=R("",null,d));0!==z.length&&(s=y.cookieEnabled?"1":"0","undefined"!=typeof y.javaEnabled&&(n=y.javaEnabled()?"1":"0"),k(a._qmeta)&&(r=";m\x3d"+B(a._qmeta),a._qmeta=null),self.screen&&(M=screen.width+"x"+screen.height+"x"+screen.colorDepth),w=new Date,x=ia(),A=ja(),a.location&&
a.location.href&&(t=B(a.location.href)),p&&p.referrer&&(l=B(p.referrer)),a.self===a.top&&(h="0"),q=sa(),u.push("/pixel;r\x3d"+f+z+A+";ns\x3d"+h+";ce\x3d"+s),u.push(";je\x3d"+n+";sr\x3d"+M+";enc\x3d"+c+";dst\x3d"+x+";et\x3d"+w.getTime()+";tzo\x3d"+w.getTimezoneOffset()+r+";ref\x3d"+l+";url\x3d"+t+";ogl\x3d"+q),m.push(u),C())};ra=function(b){var d=new Image;b=[a.location.protocol,"//pixel.",na(u)?"quantserve.com":"quantcount.com",b[0],";cm\x3d",la(u),b[1]].join("");d.alt="";d.src=b;d.onload=function(){d&&
"number"==typeof d.width&&3===d.width&&ka("__qca")}};C=function(){if(u)for(;m.length;)ra(m.shift());else qa()};na=function(a){return!0===a||1===a||1===a||k(a)&&"approved"===a.consent?!0:!1};qa=function(){if(!k(u)){if(a.top===a.self){if("object"===typeof PrivacyManagerAPI&&"function"===typeof PrivacyManagerAPI.callApi){oa("getConsent","advertising");return}}else if(a.postMessage&&"object"===typeof JSON){pa("getConsent","advertising");return}u=1}C()};oa=function(a,d){u=PrivacyManagerAPI.callApi(a,"quantserve.com",
I(),"truste.com",d);C()};pa=function(b,d){var c={PrivacyManagerAPI:{timestamp:(new Date).getTime(),action:b,self:"quantserve.com",domain:I(),authority:"truste.com",type:d}};if(a.addEventListener)a.addEventListener("message",J,!1);else if(a.attachEvent)a.attachEvent("onmessage",J);else{u=!0;C();return}try{a.top.postMessage(JSON.stringify(c),"*")}catch(f){}ha=setTimeout(function(){k(u)||(u=!0,C())},25)};J=function(b){var d=null;if(b.source===window.top){try{d="object"===typeof JSON&&JSON.parse(b.data)}catch(c){}d&&
"object"===typeof d.PrivacyManagerAPI&&(clearTimeout(ha),a.removeEventListener?window.removeEventListener("message",J,!1):a.detachEvent&&window.detachEvent("onmessage",J),u=d.PrivacyManagerAPI,C())}};ga=function(){var a=arguments,d,c;s([].slice.call(a));for(c=0;c<a.length;c++)d=a[c],q(d);t.length?K(t.slice(0)):E()};s=function(b){var d=ca(b);if("array"===d)for(d=0;d<b.length;d++)s(b[d]);else"object"===d&&ea(b.qacct||a._qacct)};va=function(){var b;a._qevents.length||a.ezt.length||"undefined"===typeof _qacct||
q({qacct:a._qacct});if(!v.evts){for(b in a._qevents)a._qevents.hasOwnProperty(b)&&q(a._qevents[b]);for(b in a.ezt)a.ezt.hasOwnProperty(b)&&q(a.ezt[b]);a._qevents={push:ga};a.ezt.push=function(){var b=arguments,c;if(k(a.queueManager))for(c=0;c<b.length;c++)a.queueManager.push(b[c]);else ga.apply(this,arguments)};v.evts=1}};Q=function(){var b;k(a._qevents)||(a._qevents=[]);k(a.ezt)||(a.ezt=[]);a._qoptions&&(b=S(a._qoptions),s(a._qoptions),a._qevents.push(b),a._qoptions=null);a.qcdata&&(b=S(a.qcdata),
s(a.qcdata),a._qevents.push(b),a.qcdata=null);a.smarttagdata&&(b=S(a.smarttagdata),s(a.smarttagdata),a._qevents.push(b),a.smarttagdata=null);v.evts||(a._qevents.push=function(){s([].slice.call(arguments));K(t.slice(0));return[].push.apply(a._qevents,arguments)},a.ezt.push=function(){s([].slice.call(arguments));K(t.slice(0));return[].push.apply(a.ezt,arguments)});s(a.ezt);s(a._qevents);s({qacct:a._qacct});a._qoptions=null;t.length?K(t.slice(0)):E();c=!0};a.quantserve=a.quantserve||Q;v.quantserve=Q;
return v}(window);
try{__qc("hasRules","p-af_gBGFZgopbs")||function(a,p,y){var F=function(a,c,e){return a?"nc"===a?!c||!e||0>c.indexOf(e):"eq"===a?c===e:"sw"===a?0===c.indexOf(e):"ew"===a?(a=c.length-e.length,c=c.lastIndexOf(e,a),-1!==c&&c===a):"c"===a?0<=c.indexOf(e):!1:!1},c=function(a,c,e){var x;if(p.top===p.self)x=y.location.href;else{x=y.referrer;var t=y.createElement("a");t.href=x;x=t.href}F(c,x,e)?a(x):a(!1)},e=function(a){return"array"==={}.toString.call(a).match(/\s([a-zA-Z]+)/)[1].toLowerCase()?{labels:a.join(",")}:
{labels:""+a}};__qc("rules",[a,null,[[e,"New York.NYC Crime"]],[[c,"c","nydailynews.com/new-york/nyc-crime"]]],[a,null,[[e,"New York.Brooklyn"]],[[c,"c","nydailynews.com/new-york/brooklyn"]]],[a,null,[[e,"New York.Bronx"]],[[c,"c","nydailynews.com/new-york/bronx"]]],[a,null,[[e,"New York.Weather"]],[[c,"c","nydailynews.com/new-york/weather"]]],[a,null,[[e,"New York.Manhattan"]],[[c,"c","nydailynews.com/new-york/manhattan"]]],[a,null,[[e,"New York.Queens"]],[[c,"c","nydailynews.com/new-york/queens"]]],
[a,null,[[e,"New York.Education"]],[[c,"c","nydailynews.com/new-york/education"]]],[a,null,[[e,"New York.Obituaries"]],[[c,"c","obituaries.nydailynews.com/obituaries/nydailynews/"]]],[a,null,[[e,"Sports.Yankees"]],[[c,"c","nydailynews.com/sports/baseball/yankees"]]],[a,null,[[e,"Sports.Giants"]],[[c,"c","nydailynews.com/sports/football/giants"]]],[a,null,[[e,"Sports.Jets"]],[[c,"c","nydailynews.com/sports/football/jets"]]],[a,null,[[e,"Sports.Knicks"]],[[c,"c","nydailynews.com/sports/basketball/knicks"]]],
[a,null,[[e,"Sports.Rangers"]],[[c,"c","nydailynews.com/sports/hockey/rangers"]]],[a,null,[[e,"Sports.Islanders"]],[[c,"c","nydailynews.com/sports/hockey/islanders"]]],[a,null,[[e,"Sports.Mets"]],[[c,"c","nydailynews.com/sports/baseball/mets"]]],[a,null,[[e,"Sports.Nets"]],[[c,"c","nydailynews.com/sports/basketball/nets"]]],[a,null,[[e,"Sports.Football"]],[[c,"c","nydailynews.com/sports/football"]]],[a,null,[[e,"Sports.Basketball"]],[[c,"c","nydailynews.com/sports/basketball"]]],[a,null,[[e,"Sports.Baseball"]],
[[c,"c","nydailynews.com/sports/baseball"]]],[a,null,[[e,"Sports.Hockey"]],[[c,"c","nydailynews.com/sports/hockey"]]],[a,null,[[e,"Sports.Soccer"]],[[c,"c","nydailynews.com/sports/soccer"]]],[a,null,[[e,"Sports.College"]],[[c,"c","nydailynews.com/sports/college"]]],[a,null,[[e,"Sports.High School"]],[[c,"c","nydailynews.com/sports/high-school"]]],[a,null,[[e,"Sports.The Score"]],[[c,"c","nydailynews.com/sports/the-score"]]],[a,null,[[e,"Sports.More Sports"]],[[c,"c","nydailynews.com/sports/more-sports"]]],
[a,null,[[e,"News.Crime"]],[[c,"c","nydailynews.com/news/crime"]]],[a,null,[[e,"News.US"]],[[c,"c","nydailynews.com/news/national"]]],[a,null,[[e,"News.World"]],[[c,"c","nydailynews.com/news/world"]]],[a,null,[[e,"News.Politics"]],[[c,"c","nydailynews.com/news/politics"]]],[a,null,[[e,"Entertainment.Gossip"]],[[c,"c","nydailynews.com/entertainment/gossip"]]],[a,null,[[e,"Entertainment.Games"]],[[c,"c","http://games.nydailynews.com/"]]],[a,null,[[e,"Entertainment.Pics"]],[[c,"c","nydailynews.com/photos/entertainment"]]],
[a,null,[[e,"Entertainment.TV"]],[[c,"c","nydailynews.com/entertainment/tv"]]],[a,null,[[e,"Entertainment.Movies"]],[[c,"c","nydailynews.com/entertainment/movies"]]],[a,null,[[e,"Entertainment.Music"]],[[c,"c","nydailynews.com/entertainment/music"]]],[a,null,[[e,"Entertainment.Theater \x26 Arts"]],[[c,"c","nydailynews.com/entertainment/theater-arts"]]],[a,null,[[e,"Autos.Buyers Guide"]],[[c,"c","nydailynews.com/autos/buyers-guide"]]],[a,null,[[e,"Horoscopes.Daily"]],[[c,"c","nydailynews.com/life-style/horoscopes/daily"]]],
[a,null,[[e,"Horoscopes.Weekly"]],[[c,"c","nydailynews.com/life-style/horoscopes/weekly"]]],[a,null,[[e,"Horoscopes.Monthly"]],[[c,"c","nydailynews.com/life-style/horoscopes/monthly"]]],[a,null,[[e,"Lifestyle.Food"]],[[c,"c","nydailynews.com/life-style/eats"]]],[a,null,[[e,"Lifestyle.Homes"]],[[c,"c","nydailynews.com/life-style/real-estate"]]],[a,null,[[e,"Lifestyle.Health"]],[[c,"c","nydailynews.com/life-style/health"]]],[a,null,[[e,"Lifestyle.Viva"]],[[c,"c","nydailynews.com/latino"]]],[a,null,
[[e,"Opinion"]],[[c,"c","nydailynews.com/opinion"]]],[a,null,[[e,"Autos.Ratings \x26 Reviews"]],[[c,"c","nydailynews.com/autos/latest-reviews"]]],[a,null,[[e,"Autos.News \x26 Views"]],[[c,"c","nydailynews.com/autos/news"]]],[a,null,[[e,"Autos.Photos \x26 Galleries"]],[[c,"c","nydailynews.com/autos/car-photos-videos"]]],[a,null,[[e,"Covers"]],[[c,"c","nydailynews.com/new-york/nydn-front-pages-2016-gallery-1.2482879"]]],[a,null,[[e,"Classifieds"]],[[c,"c","classifieds.nydailynews.com"]]])}("p-af_gBGFZgopbs",
window,document)}catch(nfe$$3){}quantserve();try{window.smarttagdata&&window._qevents.push(window.smarttagdata),window.qcdata&&window._qevents.push(window.qcdata)}catch(nfe$$4){};