(function(window){var l="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(c.get||c.set)throw new TypeError("ES3 does not support getters and setters.");a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},p="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function t(){t=function(){};p.Symbol||(p.Symbol=u)}var v=0;function u(a){return"jscomp_symbol_"+(a||"")+v++}
function y(){t();var a=p.Symbol.iterator;a||(a=p.Symbol.iterator=p.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&l(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return z(this)}});y=function(){}}function z(a){var b=0;return D(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function D(a){y();a={next:a};a[p.Symbol.iterator]=function(){return this};return a}function E(a){y();var b=a[Symbol.iterator];return b?b.call(a):z(a)}
function F(a,b){if(b){for(var c=p,d=a.split("."),e=0;e<d.length-1;e++){var f=d[e];f in c||(c[f]={});c=c[f]}d=d[d.length-1];e=c[d];f=b(e);f!=e&&null!=f&&l(c,d,{configurable:!0,writable:!0,value:f})}}function I(a,b){return Object.prototype.hasOwnProperty.call(a,b)}F("Object.assign",function(a){return a?a:function(a,c){for(var b=1;b<arguments.length;b++){var e=arguments[b];if(e)for(var f in e)I(e,f)&&(a[f]=e[f])}return a}});
function J(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{w:e,H:f}}return{w:-1,H:void 0}}F("Array.prototype.find",function(a){return a?a:function(a,c){return J(this,a,c).H}});F("Array.from",function(a){return a?a:function(a,c,d){y();c=c?c:function(a){return a};var b=[],f=a[Symbol.iterator];if("function"==typeof f)for(a=f.call(a);!(f=a.next()).done;)b.push(c.call(d,f.value));else for(var f=a.length,g=0;g<f;g++)b.push(c.call(d,a[g]));return b}});
F("WeakMap",function(a){function b(a){this.a=(f+=Math.random()+1).toString();if(a){t();y();a=E(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}}function c(a){I(a,e)||l(a,e,{value:{}})}function d(a){var b=Object[a];b&&(Object[a]=function(a){c(a);return b(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),f=new a([[b,2],[c,3]]);if(2!=f.get(b)||3!=f.get(c))return!1;f["delete"](b);f.set(c,4);return!f.has(b)&&4==f.get(c)}catch(G){return!1}}())return a;
var e="$jscomp_hidden_"+Math.random().toString().substring(2);d("freeze");d("preventExtensions");d("seal");var f=0;b.prototype.set=function(a,b){c(a);if(!I(a,e))throw Error("WeakMap key fail: "+a);a[e][this.a]=b;return this};b.prototype.get=function(a){return I(a,e)?a[e][this.a]:void 0};b.prototype.has=function(a){return I(a,e)&&I(a[e],this.a)};b.prototype["delete"]=function(a){return I(a,e)&&I(a[e],this.a)?delete a[e][this.a]:!1};return b});
F("Map",function(a){function b(){var a={};return a.h=a.next=a.head=a}function c(a,b){var c=a.a;return D(function(){if(c){for(;c.head!=a.a;)c=c.h;for(;c.next!=c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})}function d(a,b){var c;c=b&&typeof b;"object"==c||"function"==c?f.has(b)?c=f.get(b):(c=""+ ++g,f.set(b,c)):c="p_"+b;var d=a.b[c];if(d&&I(a.b,c))for(var e=0;e<d.length;e++){var h=d[e];if(b!==b&&h.key!==h.key||b===h.key)return{id:c,list:d,index:e,c:h}}return{id:c,
list:d,index:-1,c:void 0}}function e(a){this.b={};this.a=b();this.size=0;if(a){a=E(a);for(var c;!(c=a.next()).done;)c=c.value,this.set(c[0],c[1])}}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(E([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var f=c.entries(),d=f.next();if(d.done||d.value[0]!=b||"s"!=d.value[1])return!1;d=f.next();return d.done||4!=d.value[0].x||"t"!=d.value[1]||
!f.next().done?!1:!0}catch(B){return!1}}())return a;t();y();var f=new WeakMap;e.prototype.set=function(a,b){var c=d(this,a);c.list||(c.list=this.b[c.id]=[]);c.c?c.c.value=b:(c.c={next:this.a,h:this.a.h,head:this.a,key:a,value:b},c.list.push(c.c),this.a.h.next=c.c,this.a.h=c.c,this.size++);return this};e.prototype["delete"]=function(a){a=d(this,a);return a.c&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.b[a.id],a.c.h.next=a.c.next,a.c.next.h=a.c.h,a.c.head=null,this.size--,!0):!1};e.prototype.clear=
function(){this.b={};this.a=this.a.h=b();this.size=0};e.prototype.has=function(a){return!!d(this,a).c};e.prototype.get=function(a){return(a=d(this,a).c)&&a.value};e.prototype.entries=function(){return c(this,function(a){return[a.key,a.value]})};e.prototype.keys=function(){return c(this,function(a){return a.key})};e.prototype.values=function(){return c(this,function(a){return a.value})};e.prototype.forEach=function(a,b){for(var c=this.entries(),f;!(f=c.next()).done;)f=f.value,a.call(b,f[1],f[0],this)};
e.prototype[Symbol.iterator]=e.prototype.entries;var g=0;return e});
F("Set",function(a){function b(a){this.a=new Map;if(a){a=E(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.a.size}if(function(){if(!a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(E([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=b||f.value[1]!=b)return!1;f=e.next();return f.done||f.value[0]==b||4!=f.value[0].x||f.value[1]!=f.value[0]?
!1:e.next().done}catch(g){return!1}}())return a;t();y();b.prototype.add=function(a){this.a.set(a,a);this.size=this.a.size;return this};b.prototype["delete"]=function(a){a=this.a["delete"](a);this.size=this.a.size;return a};b.prototype.clear=function(){this.a.clear();this.size=0};b.prototype.has=function(a){return this.a.has(a)};b.prototype.entries=function(){return this.a.entries()};b.prototype.values=function(){return this.a.values()};b.prototype.keys=b.prototype.values;b.prototype[Symbol.iterator]=
b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.a.forEach(function(f){return a.call(b,f,f,c)})};return b});
F("Promise",function(a){function b(a){this.b=0;this.l=void 0;this.a=[];var b=this.g();try{a(b.resolve,b.reject)}catch(h){b.reject(h)}}function c(){this.a=null}if(a)return a;c.prototype.b=function(a){this.a||(this.a=[],this.g());this.a.push(a)};c.prototype.g=function(){var a=this;this.f(function(){a.l()})};var d=p.setTimeout;c.prototype.f=function(a){d(a,0)};c.prototype.l=function(){for(;this.a&&this.a.length;){var a=this.a;this.a=[];for(var b=0;b<a.length;++b){var c=a[b];delete a[b];try{c()}catch(k){this.j(k)}}}this.a=
null};c.prototype.j=function(a){this.f(function(){throw a;})};b.prototype.g=function(){function a(a){return function(f){c||(c=!0,a.call(b,f))}}var b=this,c=!1;return{resolve:a(this.R),reject:a(this.j)}};b.prototype.R=function(a){if(a===this)this.j(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof b)this.X(a);else{var c;a:switch(typeof a){case "object":c=null!=a;break a;case "function":c=!0;break a;default:c=!1}c?this.O(a):this.B(a)}};b.prototype.O=function(a){var b=void 0;
try{b=a.then}catch(h){this.j(h);return}"function"==typeof b?this.Z(b,a):this.B(a)};b.prototype.j=function(a){this.C(2,a)};b.prototype.B=function(a){this.C(1,a)};b.prototype.C=function(a,b){if(0!=this.b)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.b);this.b=a;this.l=b;this.N()};b.prototype.N=function(){if(this.a){for(var a=this.a,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.a=null}};var e=new c;b.prototype.X=function(a){var b=this.g();a.f(b.resolve,b.reject)};b.prototype.Z=
function(a,b){var c=this.g();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};b.prototype.then=function(a,c){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(q){f(q)}}:b}var e,f,g=new b(function(a,b){e=a;f=b});this.f(d(a,e),d(c,f));return g};b.prototype["catch"]=function(a){return this.then(void 0,a)};b.prototype.f=function(a,b){function c(){switch(d.b){case 1:a(d.l);break;case 2:b(d.l);break;default:throw Error("Unexpected state: "+d.b);}}var d=this;this.a?this.a.push(function(){e.b(c)}):
e.b(c)};b.resolve=function(a){return a instanceof b?a:new b(function(b){b(a)})};b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(c,d){for(var e=E(a),f=e.next();!f.done;f=e.next())b.resolve(f.value).f(c,d)})};b.all=function(a){var c=E(a),d=c.next();return d.done?b.resolve([]):new b(function(a,e){function f(b){return function(c){g[b]=c;h--;h||a(g)}}var g=[],h=0;do g.push(void 0),h++,b.resolve(d.value).f(f(g.length-1),e),d=c.next();while(!d.done)})};b.$jscomp$new$AsyncExecutor=
function(){return new c};return b});F("Array.prototype.findIndex",function(a){return a?a:function(a,c){return J(this,a,c).w}});function K(a){for(var b in a)a.hasOwnProperty(b)&&(a[b]||delete a[b]);return Object.keys(a).map(function(b){return b+"\x3d"+a[b]}).join("\x26")}function L(a){return a.substring(a.indexOf("?")+1).split("\x26").reduce(function(a,c){var b=c.split("\x3d");a[b[0]]=b[1];return a},{})};function M(a){var b=Math.pow(10,3);return Math.round(a*b)/b}function O(){var a=0;return function(){a++;return a}};function P(a){return a?[["edge",/Edge\/([0-9\._]+)/],["yandexbrowser",/YaBrowser\/([0-9\._]+)/],["chrome",/(?!Chrom.*OPR)Chrom(?:e|ium)\/([0-9\.]+)(:?\s|$)/],["crios",/CriOS\/([0-9\.]+)(:?\s|$)/],["firefox",/Firefox\/([0-9\.]+)(?:\s|$)/],["opera",/Opera\/([0-9\.]+)(?:\s|$)/],["opera",/OPR\/([0-9\.]+)(:?\s|$)$/],["ie",/Trident\/7\.0.*rv\:([0-9\.]+)\).*Gecko$/],["ie",/MSIE\s([0-9\.]+);.*Trident\/[4-7].0/],["ie",/MSIE\s(7\.0)/],["bb10",/BB10;\sTouch.*Version\/([0-9\.]+)/],["android",/Android\s([0-9\.]+)/],
["ios",/Version\/([0-9\._]+).*Mobile.*Safari.*/],["safari",/Version\/([0-9\._]+).*Safari/]].map(function(b){if(b[1].test(a)){var c=b[1].exec(a);(c=c&&c[1].split(/[._]/).slice(0,3))&&3>c.length&&Array.prototype.push.apply(c,1==c.length?[0,0]:[0]);return{name:b[0],version:parseFloat(c.join("."))}}}).filter(Boolean).shift():null}function Q(){this.a={}}Q.prototype.i=function(a){a&&a.name&&(this.a[a.name]=a)};Q.prototype.addIncludedBrowser=Q.prototype.i;
Q.prototype.check=function(a){if(!a||!a.name)return!1;var b=this.a[a.name]||void 0;return!!b&&(!b.m||b.m&&a.version>=b.m)&&(!b.o||b.o&&a.version<=b.o)};Q.prototype.check=Q.prototype.check;function R(a,b,c){this.name=a;this.m=b;this.o=c}R.prototype.T=function(a){"number"===typeof a&&(this.m=a)};R.prototype.setEarliestVersion=R.prototype.T;R.prototype.U=function(a){"number"===typeof a&&(this.o=a)};R.prototype.setLatestVersion=R.prototype.U;function S(a,b){var c={method:"GET",withCredentials:!0},c=void 0===c?{}:c;try{var d,e=!1,f=c.method||"GET";window.XMLHttpRequest?(d=new window.XMLHttpRequest,void 0===d.responseType&&(e=!0)):e=!0;e?(d=new window.XDomainRequest,d.onload=function(){b(d.responseText,d)},d.onerror=function(){console.log("xhr onerror")},d.ontimeout=function(){console.log("xhr timeout")},d.onprogress=function(){console.log("xhr onprogress")}):d.onreadystatechange=function(){4===d.readyState&&b&&b(d.responseText,d)};if("GET"===
f){var g=aa(a);a=ba(g)}d.open(f,a);e||(c.withCredentials&&(d.withCredentials=!0),c.ba&&d.setRequestHeader("X-Requested-With","XMLHttpRequest"),d.setRequestHeader("Content-Type",c.contentType||"text/plain"));d.send(void 0);return!0}catch(h){return console.error("xhr construction",h),!1}}function ca(a){var b=new Q;b.i(new R("chrome",4));b.i(new R("safari",4));b.i(new R("firefox",3.5));b.i(new R("ie",10));b.i(new R("edge"));return b.check(a)}
function aa(a){var b=document.createElement("a");b.href=decodeURIComponent(a);return{protocol:(b.protocol||"").replace(/:$/,""),hostname:b.hostname,port:+b.port,pathname:b.pathname&&b.pathname.replace(/^(?!\/)/,"/"),search:da(b.search||""),hash:(b.hash||"").replace(/^#/,""),host:b.host}}function ba(a){return(a.protocol||"http")+"://"+(a.host||a.hostname+(a.port?":"+a.port:""))+(a.pathname||"")+(a.search?"?"+ea(a.search||""):"")+(a.hash?"#"+a.hash:"")}
function da(a){return a?a.replace(/^\?/,"").split("\x26").reduce(function(a,c){var b=E(c.split("\x3d")),e=b.next().value,b=b.next().value;/\[\]$/.test(e)?(e=e.replace("[]",""),a[e]=a[e]||[],a[e].push(b)):a[e]=b||"";return a},{}):{}}function ea(a){return Object.keys(a).filter(function(a){return"callback"!==a&&"jsonp"!==a}).map(function(b){return Array.isArray(a[b])?a[b].map(function(a){return b+"[]\x3d"+a}).join("\x26"):b+"\x3d"+a[b]}).join("\x26")};function T(a){var b=document.createElement("script");b.async=!0;b.src=a;a=document.getElementsByTagName("script")[0];a.parentNode.insertBefore(b,a)};function fa(a,b){return a.map(function(a){return a.oxAdUnitId&&"display"===a.type||U(a)?a:b.find(function(b){return a.getSlotElementId&&b.divId===a.getSlotElementId()})}).filter(function(a){return a})}function ga(a){return a.reduce(function(a,c){U(c)?a[1].push(c):a[0].push(c);return a},[[],[]])}function U(a){return a.oxAdUnitId&&"video"===a.type};function V(a){return a.reduce(function(a,c){return a.concat(Array.isArray(c)?V(c):c)},[])};var ha=O();
function W(a,b){a=a?a:{};b=b?b:{};this.id=ha();this.adUnit=a;this.adMapping=b;this.f=1;this.a="initialized";U(b)?(this.type="video",this.b=a.cache_key,this.pub_rev=a.pub_rev?1E3*parseFloat(a.pub_rev):0,this.cpm=a.pub_rev?M(parseFloat(a.pub_rev)):0,this.per_colo_domain=a.per_colo_domain,this.ph=a.ph):(this.type="display",this.divId=b.divId,this.b=a.ts,this.pub_rev=a.pub_rev?parseInt(a.pub_rev,10):0,this.cpm=a.pub_rev?M(parseInt(a.pub_rev,10)/1E3):0,this.ad=a.html,this.g=a.deal_id,a.creative&&0<a.creative.length?
(this.width=parseInt(a.creative[0].width,10),this.height=parseInt(a.creative[0].height,10),this.tracking=a.creative[0].tracking):b.sizes&&0<b.sizes.length&&(this.width=b.sizes[0][0],this.height=b.sizes[0][1]))}W.prototype.s=function(){var a=[X(this.cpm)];this.g&&a.push(this.g);a=a.join(",");return[this.width+"x"+this.height,a].join("_")};W.prototype.getOxTargetingValue=W.prototype.s;W.prototype.u=function(){return[this.width+"x"+this.height,X(this.adUnit&&this.adUnit.tbd||0)].join("_")};
W.prototype.getSmartFloorTargetingValue=W.prototype.u;W.prototype.v=function(){return!(!this.adUnit||!this.adUnit.tbd)};W.prototype.hasSmartFloor=W.prototype.v;W.prototype.L=function(a){return this.S<(a||(new Date).getTime())-27E4};W.prototype.isExpired=W.prototype.L;W.prototype.G=function(){this.a="targeted"};W.prototype.setTargeted=W.prototype.G;W.prototype.M=function(){return"targeted"===this.a};W.prototype.isTargeted=W.prototype.M;W.prototype.F=function(){this.a="displayed"};
W.prototype.setDisplayed=W.prototype.F;W.prototype.P=function(){this.a="initialized"};W.prototype.resetBidState=W.prototype.P;W.prototype.A=function(){return"displayed"===this.a};W.prototype.isDisplayed=W.prototype.A;function X(a){a=1E3*a/1;var b=Math.min(a,2E4);0<b&&25>b&&(b=25);return 1E3>a?5*Math.round(b/50):5E3>a?10*Math.round(b/100):50*Math.round(b/500)};function ia(a,b){Object.keys(b).forEach(function(c){var d=["c",c].join(".");c=Array.from(b[c]).filter(function(a){return a}).join(",");a[d]=c});return a}
function ja(a){return a.map(function(a){if(a&&a.customVariables)return Object.keys(a.customVariables).map(function(b){var c=a.customVariables[b],e=new Set;Array.isArray(c)?e=c.filter(function(a){return"string"===typeof a}).reduce(function(a,b){return a.add(b)},e):"string"===typeof c&&e.add(c);return{key:b,value:e}})}).reduce(function(a,c){function b(a,b){for(var c=E(b),d=c.next();!d.done;d=c.next())a.add(d.value);return a}return c?c.reduce(function(a,c){var d={};return Object.assign({},a,(d[c.key]=
b(a[c.key]||new Set,c.value),d))},a):a},{})}function ka(a,b,c,d){var e={};e.url=b.location.href&&encodeURIComponent(b.location.href);e.be=!0;e.auid=a.oxAdUnitId;e.bc="hb_lite_0.2.3";c&&(e.jsonp=c);d&&(e.tid=d);return K(e)}function la(a){var b=a.reduce(function(a,b){if(!a[b.oxAdUnitId]&&b.floor||a[b.oxAdUnitId]<b.floor)a[b.oxAdUnitId]=b.floor;return a},{});return Object.keys(b).reduce(function(a,d){a.push(d+":"+Math.round(1E3*b[d]));return a},[]).join(",")}
function ma(a){return a.map(function(a){return a.oxAdUnitId}).join("%2C")}function na(a){return a.map(function(a){return Array.isArray(a.sizes)?a.sizes.map(function(a){return Array.isArray(a)?a[0]+"x"+a[1]:String(a)}).join(","):String(a.sizes)}).join("|")};var oa=O();function pa(a,b){var c=(b&&b.document||window.document).body;c&&c.appendChild(qa(a,b))}function Y(a,b,c,d,e){var f=a.tracking&&a.tracking.impression.match(/([^?]+\/)ri\?/),g={};g.bd=+new Date-b;g.bp=a.pub_rev;g.bs=d;g.bsq=a.f;g.bt=c;g.ca=0;g.ts=a.b;g.br=e?"t":a.pub_rev?"p":"0";f&&((new Image).src=f[1]+"bo?"+K(g),a.f++)}
function qa(a,b){var c=(b&&b.document||window.document).createElement("iframe");c.id="openx-pd"+oa();c.width="0";c.height="0";c.border="0px";c.frameBorder="0";c.hspace="0";c.marginHeight="0";c.marginWidth="0";c.scrolling="no";c.src=a||"about:blank";c.style.border="0";c.style.display="none";c.vspace="0";return c};function Z(a,b){this.adMappings=[];this.a=[];this.b=O();this.g=O();this.deliveryDomain="";this.singleRequest=!1;this.namespace="oxhbjs";this.timeLimit=2500;this.window=b||window;this.f=ca(P(this.window.navigator.userAgent));this.D(a);this.cmds={push:function(a){return a()}};return this}
Z.prototype.D=function(a){a=void 0===a?{}:a;this.deliveryDomain=a.deliveryDomain;this.timeLimit=a.timeLimit||this.timeLimit;this.singleRequest=void 0!==a.singleRequest?a.singleRequest:this.singleRequest;this.namespace=a.namespace||this.namespace;this.window[this.namespace]=this.window[this.namespace]||{};this.adMappings=a.adMappings||this.adMappings;this.contentTopicId=void 0!==a.contentTopicId?a.contentTopicId:this.contentTopicId;return this};Z.prototype.setConfig=Z.prototype.D;
Z.prototype.K=function(a,b){function c(a,b,c,d){return new Promise(function(g){if(a){var h=(new Date).valueOf(),n="videoAdResponseHandler"+f.g(),k=ka(a,d,"window."+b+"."+n,G);d[b][n]=function(a,b,c,d){var e=!1,g=setTimeout(function(){e||(e=!0,d())},b);return function(n){var k=n;if("string"===typeof n)try{k=JSON.parse(n)}catch(ta){k={pub_rev:"",cache_key:"",per_colo_domain:"",ph:""}}n=new W({pub_rev:k.pub_rev,cache_key:k.cache_key,per_colo_domain:k.per_colo_domain,ph:k.ph},a);e||(e=!0,clearTimeout(g),
d(n));f.a.push(n);Y(n,h,b,c,e)}}(a,c,d.location.hostname,g);T("//"+e+"/v/1.0/av?"+k)}else g()})}a=a?a:{};var d=this,e=a.deliveryDomain||this.deliveryDomain;if(!e)return console.error("OX Header Bidder: getBids() Error: deliveryDomain not defined"),new Promise(function(a){a([])});var f=this,g=a.timeLimit||this.timeLimit,h=void 0!==a.singleRequest?a.singleRequest:this.singleRequest,k=[],G=a.contentTopicId||this.contentTopicId,A=[];Array.isArray(a.adMappings)?A=fa(a.adMappings,this.adMappings):A=this.adMappings;
var B=E(ga(A)),A=B.next().value,B=B.next().value;k.push(function(a,b,c,d,g){return new Promise(function(h){function k(a,b,c){var d=!1,e=setTimeout(function(){d||(d=!0,c(q))},b);return function(h){var k=h;if("string"===typeof h)try{k=JSON.parse(h)}catch(w){k={ads:{ad:[],count:0,pixels:"",version:-1}}}h={ads:{ad:k.ads&&k.ads.ad,count:k.ads&&k.ads.count,pixels:k.ads&&k.ads.pixels,version:k.ads&&k.ads.version}};var m=d,k=ra(a,h.ads.ad||[]);H--;q=q.concat(k);d||H||(d=!0,clearTimeout(e),c(q));f.a=f.a.concat(k);
h.ads&&h.ads.pixels&&pa(h.ads.pixels,g);k.forEach(function(a){Y(a,n,b,g.location.hostname,m)})}}if(b.length&&b.length){var n=(new Date).valueOf(),H=a?1:b.length,q=[],A;b=a?[b]:b;b.forEach(function(b){var n=f.b();A="window."+c+".displayAdResponseHandler"+n;b=a?b:[b];var r;r=b;var q=A,H=G;if(Array.isArray(r)){var B=la(r),C=g.self!==g.top,m={};m.auid=ma(r);m.aus=na(r);m.bc="hb_lite_0.2.3";m.be=1;m.ch=g.document.a||g.document.characterSet;m.ifr=C;m.jr=g.document.referrer;m.ju=g.location.href&&encodeURIComponent(g.location.href);
m.res=g.screen.width+"x"+g.screen.height+"x"+g.screen.colorDepth;var w,x;x=g;w=g.document;var N;C?(x=g.top,w=g.top.document,C=w.documentElement,N=w.body,w=x.innerWidth||C.clientWidth||N.clientWidth,x=x.innerHeight||C.clientHeight||N.clientHeight):(C=w.documentElement,w=x.innerWidth||C.clientWidth,x=x.innerHeight||C.clientHeight);m.tws=w+"x"+x;m.tz=(new Date).getTimezoneOffset();m.nocache=(new Date).getTime();q&&(m.callback=q);m=ia(m,ja(r));B&&(m.aumf=B);H&&(m.tid=H);r=K(m)}else r="";r="//"+e+"/w/1.0/arj?"+
r;b=k(b,d,h);n="displayAdResponseHandler"+n;q=!0;f.f&&(q=!S(r,b));q&&(g[c][n]=b,T(r))})}else h([])})}(h,A,this.namespace,g,this.window));h=B.map(function(a){return c(a,d.namespace,g,d.window)});return Promise.all(k.concat(h)).then(function(a){var c=(new Date).getTime();a=V(a).filter(function(a){return a}).map(function(a){a.S=c;return a});b&&b(a);return a})};Z.prototype.getBids=Z.prototype.K;
Z.prototype.V=function(a,b){if(a){var c=function(a,b){var c=a.getSlotElementId();return b.find(function(a){return a.divId===c&&!a.J&&!a.A()})||null}(a,b),d=function(a,b){return b?a.getSizes().some(function(a){return a.getWidth()===b.width&&a.getHeight()===b.height}):!1}(a,c),e;e=a.getSizes()[0].getWidth()+"x"+a.getSizes()[0].getHeight();e=c?d?c.s():e+"_0":e+"_t";try{a.setTargeting("oxb",e),c&&d&&(a.setTargeting("oxb_bid_id",c.id.toString()),a.setTargeting("oxb_bid_namespace",this.namespace),c.v()&&
a.setTargeting("oxb1",c.u()),c.G())}catch(f){console.error("AuctionEvents.ERROR","Unexpected error in setOxTargeting",f)}}};Z.prototype.setOxTargetingForGoogletagSlot=Z.prototype.V;
Z.prototype.W=function(a,b,c){var d=b.oxb_bid_id&&parseInt(b.oxb_bid_id[0],10);if((a=c.document)&&d)try{var e=this.a.find(function(a){return a.id===d});if(e){e.F();e.J=e.Y=!0;var f=e.height,g=e.width,h=e.$,k=e.ad;a===document||"video"===e.aa?console.error("Error trying to write ad. Ad render call ad id "+d+" was prevented from writing to the main document."):k?(a.write(k),a.close(),a.defaultView&&a.defaultView.frameElement&&(a.defaultView.frameElement.width=g,a.defaultView.frameElement.height=f)):
h?(a.write('\x3cIFRAME SRC\x3d"'+h+'" FRAMEBORDER\x3d"0" SCROLLING\x3d"no" MARGINHEIGHT\x3d"0" MARGINWIDTH\x3d"0" TOPMARGIN\x3d"0" LEFTMARGIN\x3d"0" ALLOWTRANSPARENCY\x3d"true" WIDTH\x3d"'+g+'" HEIGHT\x3d"'+f+'"\x3e\x3c/IFRAME\x3e'),a.close(),a.defaultView&&a.defaultView.frameElement&&(a.defaultView.frameElement.width=g,a.defaultView.frameElement.height=f)):console.error("Error trying to write ad. No ad for bid response id: "+d)}else console.error("Error trying to write ad. Cannot find ad by given id : "+
d)}catch(G){console.error("Error trying to write ad Id :"+d+" to the page:"+G.message)}else console.error("Error trying to write ad Id :"+d+" to the page. Missing document or adId")};Z.prototype.showAd=Z.prototype.W;
Z.prototype.I=function(a,b){a=void 0===a?"":a;if(!b)return a;var c=a.substring(0,a.indexOf("?")+1),d=L(a),e=encodeURIComponent("ff\x3d"+b.b+"\x26oxcolo\x3d"+b.per_colo_domain+"\x26oxph\x3d"+b.ph+"\x26oxb\x3d"+d.sz+"v_"+X(b.cpm));d.url=window.location.href&&encodeURIComponent(window.location.href);d.description_url=window.location.hostname&&encodeURIComponent(window.location.hostname);d.cust_params=d.cust_params?d.cust_params+"%26"+e:e;return c+K(d)};Z.prototype.buildVastUrl=Z.prototype.I;
function ra(a,b){var c=b.slice();return a.map(function(a){var b=c.findIndex(function(b){return String(a.oxAdUnitId)===String(b.adunitid)&&sa(b,a)&&!b.Y});if(0<=b){if(b=c.splice(b,1)[0],b.pub_rev)return new W(b,a)}else return new W(void 0,a)}).filter(function(a){return a})}function sa(a,b){var c=a.creative&&a.creative[0];return b.sizes&&b.sizes.length?c?b.sizes.some(function(a){if(!a)return!1;var b=E(a);a=b.next().value;b=b.next().value;return a==c.width&&b==c.height}):!1:!0};window.HeaderBidder=Z;})(window)
//# sourceMappingURL=hb-lite.min.js.map
