// Copyright 2012 Google Inc. All rights reserved.
// Container Version: 8
(function(w,g){w[g]=w[g]||{};})(window,'google_tag_manager');(function(){


var __c;(function(){(function(a){__c=a;__c.a="c";__c.b=["google"];__c.c=!0})(function(a){return a["26"]})})();






var Kb=this;/*
 jQuery v1.9.1 (c) 2005, 2012 jQuery Foundation, Inc. jquery.org/license. */
var Lb=/\[object (Boolean|Number|String|Function|Array|Date|RegExp)\]/,Mb=function(a){if(null==a)return String(a);var b=Lb.exec(Object.prototype.toString.call(Object(a)));return b?b[1].toLowerCase():"object"},Nb=function(a,b){return Object.prototype.hasOwnProperty.call(Object(a),b)},Ga=function(a){if(!a||"object"!=Mb(a)||a.nodeType||a==a.window)return!1;try{if(a.constructor&&!Nb(a,"constructor")&&!Nb(a.constructor.prototype,"isPrototypeOf"))return!1}catch(c){return!1}for(var b in a);return void 0===
b||Nb(a,b)},Ea=function(a,b){var c=b||("array"==Mb(a)?[]:{}),d;for(d in a)if(Nb(a,d)){var e=a[d];"array"==Mb(e)?("array"!=Mb(c[d])&&(c[d]=[]),c[d]=Ea(e,c[d])):Ga(e)?(Ga(c[d])||(c[d]={}),c[d]=Ea(e,c[d])):c[d]=e}return c};var Ca={},qb=null,Ob=Math.random();Ca.f="GTM-56FTZL";var Pb=null,xa=null,Sa=!1,Qb="//www.googletagmanager.com/a?id="+Ca.f+"&cv=8",Rb={},Sb={},Ta={};var Va,Wa,Tb,Ub,Vb,Wb,Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,gc,hc,ic,jc,kc,lc,mc,nc,oc,pc,qc,rc,sc,tc,uc,vc,wc,xc,yc,zc,Ac,Bc,Cc,Dc,Ec,Fc,Gc,Hc,Ic,Jc,Kc,Lc,Mc,Nc,Oc,Pc,Qc,Rc,Sc,Tc,Uc,Vc,Wc,Xc,Yc,Zc,$c,ad,bd,cd,dd,ed,fd,gd,hd,id,jd,kd,ld,md,nd,od,pd,qd,rd,sd,td,ud,vd,wd,xd,yd,zd,Ad,Bd,Cd,Dd,Ed,Fd,Gd,Hd,Id,Jd,Kd,Ld,Md,Nd,Od,Pd,Qd,Rd,Sd,Td,Ud,Vd,Wd,Xd,Yd,Zd,$d,ae,be,ce,de,ee,fe,ge,he,ie,je,ke,le,me,ne,oe,pe,qe,re,se,te,ue,ve,we,xe,ye,ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,Ve,We,Xe,
Ye,Ze,$e,af,bf,cf,df,ef,ff,gf,hf,jf,kf,lf,mf,nf,of,pf,qf,rf,sf,tf,uf,vf,wf,xf,yf,zf,Af,Bf,Cf,Df,Ef,Ff,Gf,Hf,If,Jf,Kf,Lf,Mf,Nf,Of,Pf;
(function(){var a=function(a){return{toString:function(){return a}}};Tb=a("");Ub=a("0");Vb="";Wb=a("");Xb=a("");Yb=a("");Zb=a("");$b=a("");ac=a("");bc=a("");cc=a("");dc=a("3");ec=a("4");fc=a("");gc=a("");hc=a("");
ic=a("");jc=a("");kc=a("");lc=a("");mc=a("");nc=a("");oc=a("");pc=a("");qc=a("");rc=a("");sc=a("");tc=a("");uc=a("");vc=a("");
wc=a("");xc=a("");yc=a("5");zc=a("");Ac=a("");Bc=a("");Cc=a("6");Dc=a("");Ec=a("");Fc=a("");Gc=a("");Hc=a("");Ic=a("");Jc=a("");Kc=a("");Lc=a("");Mc=a("");
Nc=a("");Oc=a("");Pc=a("");Qc=a("");Rc=a("");Sc=a("");Tc=a("");Uc=a("");Vc=a("");Wc=a("7");Xc=a("");Yc=a("");Zc=a("8");$c=a("");ad=a("");bd=a("");cd=a("");
dd=a("");ed=a("");fd=a("");gd=a("");hd=a("9");id=a("");jd=a("10");kd=a("");ld=a("");md=a("");nd=a("");od=a("");pd=a("");qd=a("11");rd=a("");sd=a("");
td=a("12");ud=a("13");vd=a("");wd=a("");xd=a("");yd=a("");zd=a("");Ad=a("");Bd=a("");Cd=a("");Dd=a("");Va=a("14");Ed=a("");Fd=a("29");Gd=a("30");Hd=a("");Id=a("");
Jd=a("15");Kd=a("");Ld=a("");Md=a("");Nd=a("");Od=a("");Wa=a("16");Pd=a("");Qd=a("");Rd=a("");Sd=a("");Td=a("");Ud=a("");Vd=a("");Wd=a("");Xd=a("");Yd=a("");Zd=a("17");$d=a("");ae=a("");
be=a("");ce=a("");de=a("");ee=a("");fe=a("");ge=a("");he=a("");ie=a("");je=a("18");ke=a("");le=a("");me=a("");ne=a("");oe=a("19");pe=a("");qe=a("");re=a("");se=a("");te=a("");ue=a("");
ve=a("");we=a("");xe=a("");ye=a("");ze=a("");Ae=a("");Be=a("");Ce=a("");De=a("");Ee=a("");Fe=a("");Ge=a("");He=a("");Ie=a("");Je=a("");Ke=a("");Le=a("");Me=a("");Ne=a("");
Oe=a("");Pe=a("");Qe=a("");Re=a("");Se=a("");Te=a("");Ue=a("");Ve=a("");We=a("");Xe=a("");Ye=a("");Ze=a("");$e=a("");af=a("");bf=a("21");cf=
a("");df=a("");ef=a("");ff=a("");gf=a("");hf=a("");jf=a("");kf=a("");lf=a("");mf=a("");nf=a("");of=a("");pf=a("");qf=a("");rf=a("");sf=a("");tf=a("22");
uf=a("");vf=a("");wf=a("");xf=a("");yf=a("");zf="";Af=a("");Bf=a("23");Cf=a("");Df=a("");Ef=a("");Ff=a("24");Gf=a("");Hf=a("");If=a("");Jf=a("");Kf=a("");Lf=
a("");Mf=a("");Nf=a("");Of=a("27");Pf=a("28")})();var Jb=function(a,b){Ea(a,b)},Ab=function(){},ta=function(a){return"function"==typeof a},Xa=function(a){return"[object Array]"==Object.prototype.toString.call(Object(a))},Qf=function(a){return"number"==Mb(a)&&!isNaN(a)},Rf=function(a){return/^[0-9]+$/.test(a)},nb=function(a){return"string"==Mb(a)},Sf=function(a,b){if(Array.prototype.indexOf){var c=a.indexOf(b);return"number"==typeof c?c:-1}for(var d=0;d<a.length;d++)if(a[d]===b)return d;return-1},wa=function(a){return a?a.replace(/^\s+|\s+$/g,""):
""},W=function(a){return Math.round(Number(a))||0},Ia=function(a){return"false"==String(a).toLowerCase()?!1:!!a},Tf=function(a){var b=[];if(Xa(a))for(var c=0;c<a.length;c++)b.push(String(a[c]));return b},K=function(){return new Date},Ba=function(a,b){if(!Qf(a)||!Qf(b)||a>b)a=0,b=2147483647;return Math.floor(Math.random()*(b-a+1)+a)},Uf=function(){this.prefix="gtm.";this.values={}};Uf.prototype.set=function(a,b){this.values[this.prefix+a]=b};
Uf.prototype.get=function(a){return this.values[this.prefix+a]};Uf.prototype.contains=function(a){return void 0!==this.get(a)};
var Vf=function(a,b,c){try{if(!a[de])return a[Va](a,b||Ab,c||Ab);c&&c()}catch(d){}return!1},Wf=function(a,b){function c(b,c){a.contains(b)||a.set(b,[]);a.get(b).push(c)}for(var d=wa(b).split("&"),e=0;e<d.length;e++)if(d[e]){var f=d[e].indexOf("=");0>f?c(d[e],"1"):c(d[e].substring(0,f),d[e].substring(f+1))}},Xf=function(a){var b=a?a.length:0;return 0<b?a[b-1]:""},Yf=function(a){var b=Ca.f;return function(){return a(b)}},Zf=function(a){for(var b=0;b<a.length;b++)a[b]()},Fa=function(){return"gtm"+$f()},
$f=function(){var a=qb.sequence||0;qb.sequence=a+1;return a},Ha=function(a,b,c){return a&&a.hasOwnProperty(b)?a[b]:c},eg=function(a){return null!==a&&void 0!==a&&void 0!==a.length},fg=function(a,b){0==b?a.Qb=!0:a.ja=!0;var c=a.i;a.C&&(a.C.mb[c]=b);Rb[c]&&(Rb[c].state=b)},gg=function(a,b){return"function"!=typeof String.prototype.startsWith?0===a.indexOf(b):a.startsWith(b)},hg=function(a,b){a.sort(function(a,d){return b(a,d)?-1:b(d,a)?1:0})};var C=window,P=document,jg=navigator,Ra=function(a,b){var c=C[a];C[a]=void 0===c?b:c;return C[a]},ka=function(a,b,c,d){return(d||"http:"!=C.location.protocol?a:b)+c},kg=function(a){var b=P.getElementsByTagName("script")[0]||P.body||P.head;b.parentNode.insertBefore(a,b)},ub=function(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})},u=function(a,b,c){var d=P.createElement("script");d.type="text/javascript";
d.async=!0;d.src=a;ub(d,b);c&&(d.onerror=c);kg(d);return d},sa=function(a,b){var c=P.createElement("iframe");c.height="0";c.width="0";c.style.display="none";c.style.visibility="hidden";kg(c);ub(c,b);void 0!==a&&(c.src=a);return c},J=function(a,b,c){var d=new Image(1,1);d.onload=function(){d.onload=null;b&&b()};d.onerror=function(){d.onerror=null;c&&c()};d.src=a},R=function(a,b,c,d){a.addEventListener?a.addEventListener(b,c,!!d):a.attachEvent&&a.attachEvent("on"+b,c)},na=function(a,b,c){a.removeEventListener?
a.removeEventListener(b,c,!1):a.detachEvent&&a.detachEvent("on"+b,c)},w=function(a){C.setTimeout(a,0)},wb=!1,xb=[],lg=function(a){if(!wb){var b=P.createEventObject,c="complete"==P.readyState,d="interactive"==P.readyState;if(!a||"readystatechange"!=a.type||c||!b&&d){wb=!0;for(var e=0;e<xb.length;e++)w(xb[e])}xb.push=function(){for(var a=0;a<arguments.length;a++)w(arguments[a]);return 0}}},mg=0,ng=function(){if(!wb&&140>mg){mg++;try{P.documentElement.doScroll("left"),lg()}catch(a){C.setTimeout(ng,50)}}},
fa=function(a){var b=P.getElementById(a);if(b&&ua(b,"id")!=a)for(var c=1;c<document.all[a].length;c++)if(ua(document.all[a][c],"id")==a)return document.all[a][c];return b},ua=function(a,b){return a&&b&&a.attributes&&a.attributes[b]?a.attributes[b].value:null},ib=function(a){return a.target||a.srcElement||{}},va=function(a){var b=a.innerText||a.textContent||"";b&&" "!=b&&(b=b.replace(/^[\s\xa0]+|[\s\xa0]+$/g,""));b&&(b=b.replace(/(\xa0+|\s{2,}|\n|\r\t)/g," "));return b},Db=function(a){var b=P.createElement("div");
b.innerHTML="A<div>"+a+"</div>";b=b.lastChild;for(var c=[];b.firstChild;)c.push(b.removeChild(b.firstChild));return c},jb=function(a,b){for(var c={},d=0;d<b.length;d++)c[b[d]]=!0;var e=a;for(d=0;e&&!c[String(e.tagName).toLowerCase()]&&100>d;d++)e=e.parentElement;e&&!c[String(e.tagName).toLowerCase()]&&(e=null);return e},og=!1,pg=[],qg=function(){if(!og){og=!0;for(var a=0;a<pg.length;a++)w(pg[a])}},rg=function(a){a=a||C;var b=a.location.href,c=b.indexOf("#");return 0>c?"":b.substring(c+1)},Bb=function(a){window.console&&
window.console.log&&window.console.log(a)};var sg=function(a,b){for(var c=a.split("&"),d=0;d<c.length;d++){var e=c[d].split("=");if(decodeURIComponent(e[0]).replace(/\+/g," ")==b)return decodeURIComponent(e.slice(1).join("=")).replace(/\+/g," ")}},U=function(a,b,c,d,e){var f,g=(a.protocol.replace(":","")||C.location.protocol.replace(":","")).toLowerCase();b&&(b=String(b).toLowerCase());switch(b){case "protocol":f=g;break;case "host":f=(a.hostname||C.location.hostname).split(":")[0].toLowerCase();if(c){var h=/^www\d*\./.exec(f);h&&h[0]&&(f=
f.substr(h[0].length))}break;case "port":f=String(1*(a.hostname?a.port:C.location.port)||("http"==g?80:"https"==g?443:""));break;case "path":f="/"==a.pathname.substr(0,1)?a.pathname:"/"+a.pathname;var k=f.split("/");0<=Sf(d||[],k[k.length-1])&&(k[k.length-1]="");f=k.join("/");break;case "query":f=a.search.replace("?","");e&&(f=sg(f,e));break;case "fragment":f=a.hash.replace("#","");break;default:f=a&&a.href}return f},za=function(a){var b="";if(a&&a.href){var c=a.href.indexOf("#");b=0>c?a.href:a.href.substr(0,
c)}return b},ya=function(a){var b=P.createElement("a");a&&(b.href=a);return b};var oa=function(a,b){var c=function(){};c.prototype=a.prototype;var d=new c;a.apply(d,Array.prototype.slice.call(arguments,1));return d};var ob=function(a){return encodeURIComponent(a)},da=function(a){var b=["veinteractive.com","ve-interactive.cn"];if(!a)return!1;var c=U(ya(a),"host");if(!c)return!1;for(var d=0;b&&d<b.length;d++){var e=b[d]&&b[d].toLowerCase();if(e){var f=c.length-e.length;0<f&&"."!=e.charAt(0)&&(f--,e="."+e);if(0<=f&&c.indexOf(e,f)==f)return!0}}return!1};
var S=function(a,b,c){for(var d={},e=!1,f=0;a&&f<a.length;f++)a[f]&&a[f].hasOwnProperty(b)&&a[f].hasOwnProperty(c)&&(d[a[f][b]]=a[f][c],e=!0);return e?d:null},sb=function(a,b){for(var c=[],d=0;a&&d<a.length;d++)a[d]&&a[d].hasOwnProperty(b)&&c.push(a[d][b]);return c},Da=function(a,b){Ea(a,b)},Ka=function(a){return W(a)},Eb=function(a,b){return Sf(a,b)};var tg={event:function(a){var b=a[1];if(nb(b)&&!(3<a.length)){var c;if(2<a.length){if(!Ga(a[2]))return;c=a[2]}var d=c,e={event:b};d&&(d=Ea(d,void 0),e.eventModel=d,e.eventCallback=d.eventCallback);return e}},set:function(a){var b;2==a.length&&Ga(a[1])?b=Ea(a[1],void 0):3==a.length&&nb(a[1])&&(b={},b[a[1]]=a[2]);if(b)return b._clear=!0,b},js:function(a){if(2==a.length&&a[1].getTime)return{event:"gtm.js","gtm.start":a[1].getTime()}}};var ug=new Uf,vg={},xg={set:function(a,b){Ea(wg(a,b),vg)},get:function(a){return Y(a,2)},reset:function(){ug=new Uf;vg={}}},Y=function(a,b){var c;if(2!=b)c=ug.get(a);else a:{for(var d=a.split("."),e=0,f=vg.eventModel;void 0!==f&&e<d.length;e++)f=f[d[e]];if(void 0!==f||1<e)c=f;else{var g=vg;for(e=0;e<d.length;e++){if(void 0===g[d[e]]){c=void 0;break a}g=g[d[e]]}c=g}}return c},yg=function(a,b){ug.set(a,b);Ea(wg(a,b),vg)},wg=function(a,b){for(var c={},d=c,e=a.split("."),f=0;f<e.length-1;f++)d=d[e[f]]=
{};d[e[e.length-1]]=b;return c};var zg=!1,Ag=!1;var Bg=Math.random(),Cg="0.050000">Bg;
var Dg=function(a,b){if(Cg){var c=Qb,d=function(a,b){b&&(c+=a+encodeURIComponent(b))};d("&v=","t");d("&n=",a);d("&s=",b&&b.state);d("&h=",b&&b.hideLatency);d("&g=",b&&b.gaLatency);d("&p=",b&&b.loadBy);d("&o=",b&&b.timeout);d("&l=",K().getTime()-W(Pb));c+="&sr=0.050000";d("&ps=",Bg);d("&cb=",Ba());J(c)}},Eg=Ab,Fg=function(){var a=!1;
};var Hg=function(a){var b=qb.zones;return b?b.checkState(Ca.f,a):Gg},Gg={active:!0,isWhitelisted:function(){return!0}};var Jg=Ab,Kg=[],Lg=!1,ma=function(a){return C["dataLayer"].push(a)},Mg=function(a){var b=!1;return function(){!b&&ta(a)&&w(Yf(a));b=!0}},Vg=function(){for(var a=!1;!Lg&&0<Kg.length;){Lg=!0;delete vg.eventModel;var b=Kg.shift();if(ta(b))try{b.call(xg)}catch(Ja){}else if(Xa(b))a:{var c=b;if(nb(c[0])){for(var d=c[0].split("."),e=d.pop(),f=c.slice(1),g=vg,h=0;h<d.length;h++){if(void 0===g[d[h]])break a;g=g[d[h]]}try{g[e].apply(g,f)}catch(Ja){}}}else{var k=b;if(k&&("[object Arguments]"==Object.prototype.toString.call(k)||
Object.prototype.hasOwnProperty.call(k,"callee"))){a:{var l=b;if(l.length&&nb(l[0])){var m=tg[l[0]];if(m){b=m(l);break a}}b=void 0}if(!b){Lg=!1;continue}}var n=void 0,p=void 0,t=b,v=t._clear;for(p in t)t.hasOwnProperty(p)&&"_clear"!==p&&(v&&yg(p,void 0),yg(p,t[p]));var r=!1,x=t.event;if(x){t.hasOwnProperty("gtm.uniqueEventId")||(t["gtm.uniqueEventId"]=$f(),yg("gtm.uniqueEventId",t["gtm.uniqueEventId"]));n=t["gtm.uniqueEventId"];xa=x;var E=Hg(n);if(E.active){var F=Mg(t.eventCallback),y=t.eventTimeout;
y&&C.setTimeout(F,Number(y));r=Jg(n,x,E.isWhitelisted,F,t.eventReporter)}}Pb||(Pb=t["gtm.start"])&&Eg();var I,M=t,B=n,z=x,D=vg;xa=null;a=r||a}Lg=!1}return!a},Wg=function(){var a=Vg();try{var b=C["dataLayer"].hide;if(b&&void 0!==b[Ca.f]&&b.end){b[Ca.f]=!1;var c=!0,d;for(d in b)if(b.hasOwnProperty(d)&&!0===b[d]){c=!1;break}c&&(b.end(),b.end=null)}}catch(e){}return a},Xg=function(){var a=Ra("dataLayer",[]),b=Ra("google_tag_manager",{});b=b["dataLayer"]=b["dataLayer"]||{};xb.push(function(){b.gtmDom||(b.gtmDom=!0,a.push({event:"gtm.dom"}))});pg.push(function(){b.gtmLoad||
(b.gtmLoad=!0,a.push({event:"gtm.load"}))});var c=a.push;a.push=function(){var b=[].slice.call(arguments,0);c.apply(a,b);for(Kg.push.apply(Kg,b);300<this.length;)this.shift();return Vg()};Kg.push.apply(Kg,a.slice(0));w(Wg)};var $a,Yg,Zg,fb=/(Firefox\D28\D)/g.test(jg.userAgent),ah=function(a,b){return function(c){c=c||C.event;var d=ib(c),e=!1;if(3!==c.which||"LINK_CLICK"!=a){"LINK_CLICK"==a&&(d=jb(d,["a","area"]),e=!d||!d.href||$g(d.href)||2===c.which||null==c.which&&4==c.button||c.ctrlKey||c.shiftKey||c.altKey||!0===c.metaKey);var f="FORM_SUBMIT"==a?$a:Zg;if(c.defaultPrevented||!1===c.returnValue||c.na&&c.na()){if(d){var g={simulateDefault:!1},h=ab(f,["wnc","nwnc"]);h&&bb(a,d,g,f.wt,h)}}else{if(d){g={};var k,l=ab(f,
["wnc","nwnc","nwc","wc"]);(k=bb(a,d,g,f.wt,l))||(cb(g.eventReport,f)?b=!0:e=!0);e=e||k||"LINK_CLICK"==a&&fb;g.simulateDefault=!k&&b&&!e;g.simulateDefault&&(e=gb(d,g)||e,!e&&c.preventDefault&&c.preventDefault());c.returnValue=k||!b||e;return c.returnValue}return!0}}}},bb=function(a,b,c,d,e){var f=d||2E3,g=Fb(b,a);switch(a){case "LINK_CLICK":g["gtm.triggers"]=e||"";g.event="gtm.linkClick";g.eventTimeout=f;g.eventCallback=bh(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "FORM_SUBMIT":g["gtm.triggers"]=
e||"";g.event="gtm.formSubmit";g.eventTimeout=f;g.eventCallback=ch(b,c);g.eventReporter=function(a){c.eventReport=a};break;case "CLICK":g.event="gtm.click";break;default:return!0}return ma(g)},eb=function(a){var b=a.target;if(!b)switch(String(a.tagName).toLowerCase()){case "a":case "area":case "form":b="_self"}return b},gb=function(a,b){var c=!1,d=/(iPad|iPhone|iPod)/g.test(jg.userAgent),e=eb(a).toLowerCase();switch(e){case "":case "_self":case "_parent":case "_top":var f;f=(e||"_self").substring(1);
b.targetWindow=C.frames&&C.frames[f]||C[f];break;case "_blank":d?(b.simulateDefault=!1,c=!0):(b.targetWindowName="gtm_autoEvent_"+K().getTime(),b.targetWindow=C.open("",b.targetWindowName));break;default:d&&!C.frames[e]?(b.simulateDefault=!1,c=!0):(C.frames[e]||(b.targetWindowName=e),b.targetWindow=C.frames[e]||C.open("",e))}return c},bh=function(a,b,c){return function(){b.simulateDefault&&(b.targetWindow?b.targetWindow.location.href=a.href:(c=c||K().getTime(),500>K().getTime()-c&&C.setTimeout(bh(a,
b,c),25)))}},ch=function(a,b,c){return function(){if(b.simulateDefault)if(b.targetWindow){var d;b.targetWindowName&&(d=a.target,a.target=b.targetWindowName);P.gtmSubmitFormNow=!0;db(a).call(a);b.targetWindowName&&(a.target=d)}else c=c||K().getTime(),500>K().getTime()-c&&C.setTimeout(ch(a,b,c),25)}},ab=function(a,b){for(var c=[],d=0;d<b.length;d++){var e=a[b[d]],f;for(f in e)e.hasOwnProperty(f)&&e[f]&&c.push(f)}return c.join(",")},dh=function(a,b,c,d,e){var f=e;if(!f||"0"==f){if(a.l)return;a.l=!0;
f="0"}var g=a.wt;b&&(!g||g>d)&&(a.wt=d);a[b?c?"wc":"wnc":c?"nwc":"nwnc"][f]=!0},cb=function(a,b){if(b.wnc["0"]||b.wc["0"])return!0;for(var c=0;c<eh.length;c++)if(a.passingRules[c]){var d=fh[c],e=d&&d[0]&&d[0][0]||d[1]&&d[1][0];if(e&&"0"!=e&&(b.wc[e]||b.wnc[e]))for(var f=eh[c][1],g=0;g<f.length;g++)if(a.resolvedTags[f[g]])return!0}return!1},Aa=function(a,b,c,d,e){var f,g,h=!1;switch(a){case "CLICK":if(P.gtmHasClickListenerTag)return;P.gtmHasClickListenerTag=!0;f="click";g=function(a){var b=ib(a);b&&
bb("CLICK",b,{},d)};h=!0;break;case "LINK_CLICK":b&&!Yg&&(Yg=za(P.location));dh(Zg,b||!1,c||!1,d,e);if(P.gtmHasLinkClickListenerTag)return;P.gtmHasLinkClickListenerTag=!0;f="click";g=ah(a,b||!1);break;case "FORM_SUBMIT":dh($a,b||!1,c||!1,d,e);if(P.gtmHasFormSubmitListenerTag)return;P.gtmHasFormSubmitListenerTag=!0;f="submit";g=ah(a,b||!1);break;default:return}R(P,f,g,h)},$g=function(a){if(!Yg)return!0;var b=a.indexOf("#");if(0>b)return!1;if(0==b)return!0;var c=ya(a);return Yg==za(c)},db=function(a){try{if(a.constructor&&
a.constructor.prototype)return a.constructor.prototype.submit}catch(b){}if(a.gtmReplacedFormSubmit)return a.gtmReplacedFormSubmit;P.gtmFormElementSubmitter||(P.gtmFormElementSubmitter=P.createElement("form"));return P.gtmFormElementSubmitter.submit.call?P.gtmFormElementSubmitter.submit:a.submit},Fb=function(a,b){var c={"gtm.element":a,"gtm.elementClasses":a.className,"gtm.elementId":a["for"]||ua(a,"id")||"","gtm.elementTarget":a.formTarget||a.target||""};switch(b){case "LINK_CLICK":c["gtm.elementUrl"]=
a.href;break;case "FORM_SUBMIT":var d=a.action;d&&d.tagName&&(d=a.cloneNode(!1).action);c["gtm.elementUrl"]=d;break;default:c["gtm.elementUrl"]=(a.attributes&&a.attributes.formaction?a.formAction:"")||a.action||a.href||a.src||a.code||a.codebase||""}return c},gh=function(){var a=function(a){var b=Ra("google_tag_manager",{}),d=b[a];d||(d=b[a]={},d.nwnc={},d.nwc={},d.wnc={},d.wc={},d.wt=null,d.l=!1);return d};Zg=a("linkClickMap");$a=a("formSubmitMap")};var hh=/(^|\.)doubleclick\.net$/i,ih=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,kb=function(a){for(var b=String(P.cookie).split(";"),c=[],d=0;d<b.length;d++){var e=b[d].split("="),f=wa(e[0]);if(f&&f==a){var g=wa(e.slice(1).join("="));g&&(g=decodeURIComponent(g));c.push(g)}}return c},kh=function(a,b,c,d,e,f){f&&(b=encodeURIComponent(b));var g=a+"="+b+"; ";c&&(g+="path="+c+"; ");e&&(g+="expires="+e.toGMTString()+"; ");var h;h="auto"==d?jh():[d||"none"];for(var k=0;k<h.length;k++){var l=g,m=h[k],n=c;if(hh.test(C.location.hostname)||
"/"==n&&ih.test(m))break;"none"!=h[k]&&(l+="domain="+h[k]+";");var p=P.cookie;P.cookie=l;if(p!=P.cookie||0<=Sf(kb(a),b))return!0}return!1},lh=function(a){if("none"==a)return 0;0==a.indexOf(".")&&(a=a.substr(1));return a.split(".").length},mh=function(a){var b=a;b?(1<b.length&&b.lastIndexOf("/")==b.length-1&&(b=b.substr(0,b.length-1)),0!=b.indexOf("/")&&(b="/"+b),a=b):a="/";return"/"==a?1:a.split("/").length},jh=function(){var a=U(C.location,"host",!0).split(".");if(4==a.length&&/^[0-9]*$/.exec(a[3]))return["none"];
for(var b=[],c=a.length-2;0<=c;c--)b.push(a.slice(c).join("."));b.push("none");return b};var ea=function(a){var b=P;return nh?b.querySelectorAll(a):null},oh=!1;if(P.querySelectorAll)try{var ph=P.querySelectorAll(":root");ph&&1==ph.length&&ph[0]==P.documentElement&&(oh=!0)}catch(a){}var nh=oh;var qh=/^[a-zA-Z0-9_]+$/,rh=/^[a-zA-Z0-9-_]+$/,sh=/^\d+\.fls\.doubleclick\.net$/;function th(a){return a&&"string"==typeof a&&a.match(qh)?a:"_gcl"}function uh(a){if(a){if("string"==typeof a){var b=th(a);return{Ba:b,za:b}}if(a&&"object"==typeof a)return{Ba:th(a.dc),za:th(a.aw)}}return{Ba:"_gcl",za:"_gcl"}}
function vh(a){var b=ya(C.location.href),c=U(b,"host",!1);if(c&&c.match(sh)){var d=U(b,"path");if(0==d.indexOf("/activityi")){var e=d.split(a+"=");if(1<e.length)return e[1].split(";")[0].split("?")[0]}}}function wh(a){for(var b=[],c=kb(a),d=0;d<c.length;d++){var e=c[d].split(".");3==e.length&&"GCL"==e[0]&&e[2].match(rh)&&b.push(e[2])}return b}
var ra=function(a){var b=vh("gclaw");if(b)return b.split(".");var c=uh(a);return wh(c.za+"_aw")},qa=function(a){var b=vh("gcldc");if(b)return b.split(".");var c=uh(a);return wh(c.Ba+"_dc")};var xh,yh;var Hh=function(){};var Ph;a:{Ph="G"}var Qh={"":"n",UA:"u",AW:"a",DC:"d",GTM:Ph},Rh="www.googletagmanager.com/gtm.js";
var Sh=Rh,hb=function(a,b,c){R(a,b,c,void 0)},ba=function(a,b,c){u(a,b,c)},Za={},La=function(a,b,c){var d=Za[a];if(void 0===d){var e=function(a,b){return function(){a.status=b;for(var c=2==b?a.Rb:a.Db,d=0;d<c.length;d++)C.setTimeout(c[d],0)}};d={status:1,Rb:[],Db:[],Zc:void 0};d.Fd=u(a,e(d,2),e(d,3));Za[a]=d}0===d.status&&(d.Zc(),d.status=2);2===d.status?b&&b():3===d.status?c&&c():1===d.status&&(b&&d.Rb.push(b),c&&d.Db.push(c))},ca=function(){return C.location.href},T=function(a,b){return Y(a,b||
2)},aa=function(a,b){C[a]=b},q=function(a,b,c){var d=C;b&&(void 0===d[a]||c&&!d[a])&&(d[a]=b);return d[a]},Ua=function(a,b,c){var d=b,e=c,f=uh(a);e=e||"auto";d=d||"/";var g=ya(C.location.href),h=U(g,"query",!1,void 0,"gclid"),k=U(g,"query",!1,void 0,"gclsrc");if(!h||!k){var l=U(g,"fragment");h=h||sg(l,"gclid");k=k||sg(l,"gclsrc")}if(void 0!==h&&h.match(rh)){var m=(new Date).getTime(),n=new Date(m+7776E6),p=["GCL",Math.round(m/1E3),h].join(".");k&&"aw.ds"!=k||kh(f.za+"_aw",p,d,e,n,!0);"aw.ds"!=k&&
"ds"!=k||kh(f.Ba+"_dc",p,d,e,n,!0)}},A=function(a,b,c,d){var e=!d&&"http:"==C.location.protocol;e&&(e=2!==pb());return(e?b:a)+c},ia=function(a){var b=0;return b},Gb=function(a){},ja=function(a){var b=!1;return b},Qa=function(a,b,c){},Ib=void 0,Pa=function(a){if(!Ib){var b=function(){var a=P.body;if(a)if(q("MutationObserver"))(new MutationObserver(function(){for(var a=0;a<Ib.length;a++)w(Ib[a])})).observe(a,{childList:!0,subtree:!0});else{var b=!1;hb(a,"DOMNodeInserted",function(){b||(b=!0,w(function(){b=!1;for(var a=0;a<Ib.length;a++)w(Ib[a])}))})}};
Ib=[];P.body?b():w(b)}Ib.push(a)},pa=function(a){var b=Ca.f.split("-"),c=b[0].toUpperCase(),d=Qh[c];d||(d="i");var e="";a&&"GTM"==c&&(e=b[1]);return d+"aj"+e},pb=function(){var a=Sh;a=a.toLowerCase();for(var b="https://"+a,c="http://"+a,d=1,e=P.getElementsByTagName("script"),f=0;f<e.length&&100>f;f++){var g=e[f].src;if(g){g=g.toLowerCase();if(gg(g,c))return 3;1===d&&gg(g,b)&&(d=2)}}return d};var Th=new RegExp(/^(.*\.)?(google|youtube|blogger|withgoogle)(\.com?)?(\.[a-z]{2})?\.?$/),Uh={customPixels:["nonGooglePixels"],html:["customScripts","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],customScripts:["html","customPixels","nonGooglePixels","nonGoogleScripts","nonGoogleIframes"],nonGooglePixels:[],nonGoogleScripts:["nonGooglePixels"],nonGoogleIframes:["nonGooglePixels"]},Vh={customPixels:["customScripts","html"],html:["customScripts"],customScripts:["html"],nonGooglePixels:["customPixels",
"customScripts","html","nonGoogleScripts","nonGoogleIframes"],nonGoogleScripts:["customScripts","html"],nonGoogleIframes:["customScripts","html","nonGoogleScripts"]},Wh=function(a,b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]),c.push.apply(c,b[a[d]]||[]);return c},Og=function(a){var b=Y("gtm.whitelist");
var c=b&&Wh(Tf(b),Uh),d=Y("gtm.blacklist")||Y("tagTypeBlacklist")||[];Th.test(C.location&&C.location.hostname)&&(d=Tf(d),d.push("nonGooglePixels","nonGoogleScripts"));var e=d&&Wh(Tf(d),Vh),f={};return function(g){var h=g&&g[Va];if(!h)return!0;if(void 0!==f[h.a])return f[h.a];var k=a(h.a);if(b){var l;if(l=k)a:{if(0>Sf(c,h.a))if(h.b&&0<h.b.length)for(var m=0;m<h.b.length;m++){if(0>
Sf(c,h.b[m])){l=!1;break a}}else{l=!1;break a}l=!0}k=l}var n=!1;if(d){var p;if(!(p=0<=Sf(e,h.a)))a:{for(var t=h.b||[],v=new Uf,r=0;r<e.length;r++)v.set(e[r],!0);for(r=0;r<t.length;r++)if(v.get(t[r])){p=!0;break a}p=!1}n=p}return f[h.a]=!k||n}};var _dbg=function(){return!1};_dbg.a="dbg";_dbg.b=["google"];var Xh=void 0,Yh="",Zh=0,$h=void 0,_et=function(a){var b,c=Y("gtm.element"),d=Y("event"),e=Number(K());Xh===c&&Yh===d&&Zh>e-250?b=$h:($h=b=c?va(c):"",Xh=c,Yh=d);Zh=e;return b?b:a[bd]};_et.a="et";_et.b=["google"];var _eu=function(a){var b=String(Y("gtm.elementUrl")||a[bd]||""),c=ya(b);return b};_eu.a="eu";_eu.b=["google"];var _e=function(){return xa};_e.a="e";_e.b=["google"];var ai=function(a,b){this.h=a;this.o=b};ai.prototype.toString=function(){var a=""+this.h;1<this.o&&(a=a+"-"+this.o);return a};var bi=function(a,b){this.kb=a;this.Fa=b};bi.prototype.toString=function(){return""+this.Fa+"."+this.kb};var ei=function(a,b){var c=new ci(null,a,b);di(c);return c},ci=function(a,b,c){this.zb=Math.floor(K().getTime()/864E5);this.Da=b||"auto";this.qa=c||"/";var d=lh(this.Da),e=mh(this.qa);this.J=a||new ai(d,e);this.j=[];this.F=new Uf},gi=function(a,b,c){b&&(""==c.kb?fi(a,b):(a.F.contains(b)||a.j.push(b),a.F.set(b,c)))},hi=function(a,b){for(var c=0;c<b.length;c++)gi(a,b[c][0],b[c][1])},fi=function(a,b){var c=Sf(a.j,b);0<=c&&a.j.splice(c,1);a.F.set(b,void 0)},ii=function(a){for(var b=[],c=0;c<a.j.length;c++){var d=
a.j[c];b.push([d,a.F.get(d)])}return b},ji=function(a){for(var b=0,c=0;c<a.j.length;c++)b=Math.max(b,a.F.get(a.j[c]).Fa);return 864E5*b};ci.prototype.toString=function(){if(0==this.j.length)return"";for(var a=[],b=0;b<this.j.length;b++){var c=this.j[b];a.push(""+c+"."+this.F.get(c).toString())}return"GAX1."+this.J.toString()+"."+a.join("!")};
var ki=function(a,b){for(var c=new Date,d=mh(a.qa),e=[],f=0;f<a.j.length;f++){var g=a.j[f];a.F.get(g).Fa<a.zb&&e.push(g)}for(f=0;f<e.length;f++)fi(a,e[f]);if(a.j.length>(b||10))return!1;c.setTime(ji(a));if("auto"!=a.Da)return kh("_gaexp",a.toString(),a.qa,a.Da,c);for(var h=jh(),k=0;k<h.length;k++)if("none"!=h[k]&&(a.J=new ai(lh(h[k]),d),kh("_gaexp",a.toString(),a.qa,h[k],c)))return!0;return!1},di=function(a){for(var b=a.J.h,c=a.J.o,d=kb("_gaexp"),e=[],f=0;f<d.length;f++){var g=li(a,d[f]);g&&e.push(g)}hg(e,
function(a,d){var e=a.J,f=d.J;return e.h==f.h&&e.o==f.o?!1:e.h==b&&e.o==c?!0:f.h==b&&f.o==c?!1:e.h==b?f.h!=b||e.o<f.o:f.h==b?!1:e.o==c?f.h!=b&&(f.o!=c||e.h<f.h):f.o==c?!1:e.h<f.h||e.h==f.h&&e.o<f.o});a.J=0<e.length?e[0].J:new ai(b,c);for(f=e.length-1;0<=f;f--)hi(a,ii(e[f]))},li=function(a,b){var c=b.match(/GAX1\.([^.]+).(.*)/);if(c){var d;a:{var e=(c[1]||"").split("-");if(!(0==e.length||2<e.length)){var f=wa(e[0]);if(0!=f.length){var g=2==e.length?wa(e[1]):"1";if(Rf(f)&&Rf(g)){d=new ai(W(f),W(g));
break a}}}d=void 0}if(d){for(var h=new ci(d,a.Da,a.qa),k=(c[2]||"").split("!"),l=0;l<k.length;l++){var m=k[l].split(".");if(3==m.length){if(!Rf(m[1]))return;gi(h,m[0],new bi(m[2],W(m[1])))}}return h}}};var _j=function(a){for(var b=String(a[je]).split("."),c=C,d=0;d<b.length;d++)c=c&&c[b[d]];return c};_j.a="j";_j.b=["google"];var _v=function(a){var b=Y(a[je].replace(/\\\./g,"."),a[Uc]);return void 0!==b?b:a[bd]};_v.a="v";_v.b=["google"];var _f=function(a){var b=String(Y("gtm.referrer")||P.referrer);if(!b)return b;var c=ya(b);return b};_f.a="f";_f.b=["google"];var pi=function(a){var b=C.location,c;(c=a[Rc]?a[Rc]:Y("gtm.url"))&&(b=ya(String(c)));var d=b.href,e=d.indexOf("#"),f=0>e?d:d.substr(0,e);a[Cc]&&(f=U(b,a[Cc],a[We],a[ad],a[Je]));return f},_u=pi;_u.a="u";_u.b=["google"];var _cn=function(a){return 0<=String(a[dc]).indexOf(String(a[ec]))};_cn.a="cn";_cn.b=["google"];var _eq=function(a){return String(a[dc])==String(a[ec])};_eq.a="eq";_eq.b=["google"];var lb=new String("undefined"),yb=function(a){this.resolve=function(b){for(var c=[],d=0;d<a.length;d++)c.push(a[d]===lb?b:a[d]);return c.join("")}};yb.prototype.toString=function(){return this.resolve("undefined")};yb.prototype.valueOf=yb.prototype.toString;var zi={},zb=function(a,b){var c=$f();zi[c]=[a,b];return c},Ai=function(a){var b=a?0:1;return function(a){var c=zi[a];if(c&&ta(c[b]))c[b]();zi[a]=void 0}};var Bi=String.prototype.trim?function(a){return a.trim()}:function(a){return a.replace(/^[\s\xa0]+|[\s\xa0]+$/g,"")},Ci=function(a,b){return a<b?-1:a>b?1:0};var Di;a:{var Ei=Kb.navigator;if(Ei){var Fi=Ei.userAgent;if(Fi){Di=Fi;break a}}Di=""}var Z=function(a){return-1!=Di.indexOf(a)};var Gi=function(){return Z("iPhone")&&!Z("iPod")&&!Z("iPad")};var Hi=function(a){Hi[" "](a);return a};Hi[" "]=function(){};var Ji=function(a,b){var c=Ii;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Ki=Z("Opera"),Li=Z("Trident")||Z("MSIE"),Mi=Z("Edge"),Ni;if(Ni=Z("Gecko")){var Oi;Oi=-1!=Di.toLowerCase().indexOf("webkit");Ni=!(Oi&&!Z("Edge"))}var Pi=Ni&&!(Z("Trident")||Z("MSIE"))&&!Z("Edge"),Qi,Ri=(Qi=-1!=Di.toLowerCase().indexOf("webkit"))&&!Z("Edge");Ri&&Z("Mobile");Z("Macintosh");Z("Windows");Z("Linux")||Z("CrOS");var Si=Kb.navigator||null;Si&&(Si.appVersion||"").indexOf("X11");Z("Android");Gi();Z("iPad");Z("iPod");Gi()||Z("iPad")||Z("iPod");
var Ti=function(){var a=Kb.document;return a?a.documentMode:void 0},Ui;a:{var Vi="",Wi=function(){var a=Di;if(Pi)return/rv:([^\);]+)(\)|;)/.exec(a);if(Mi)return/Edge\/([\d\.]+)/.exec(a);if(Li)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Ri)return/WebKit\/(\S+)/.exec(a);if(Ki)return/(?:Version)[ \/]?(\S+)/.exec(a)}();Wi&&(Vi=Wi?Wi[1]:"");if(Li){var Xi=Ti();if(null!=Xi&&Xi>parseFloat(Vi)){Ui=String(Xi);break a}}Ui=Vi}
var Yi=Ui,Ii={},Zi=function(a){return Ji(a,function(){for(var b=0,c=Bi(String(Yi)).split("."),d=Bi(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var g=c[f]||"",h=d[f]||"";do{var k=/(\d*)(\D*)(.*)/.exec(g)||["","","",""],l=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==k[0].length&&0==l[0].length)break;b=Ci(0==k[1].length?0:parseInt(k[1],10),0==l[1].length?0:parseInt(l[1],10))||Ci(0==k[2].length,0==l[2].length)||Ci(k[2],l[2]);g=k[3];h=l[3]}while(0==b)}return 0<=b})},$i;
var aj=Kb.document;$i=aj&&Li?Ti()||("CSS1Compat"==aj.compatMode?parseInt(Yi,10):5):void 0;var bj;if(!(bj=!Pi&&!Li)){var cj;if(cj=Li)cj=9<=Number($i);bj=cj}bj||Pi&&Zi("1.9.1");Li&&Zi("9");var Cb=function(a,b){var c="";Li&&!dj(a)&&(c='<script>document.domain="'+document.domain+'";\x3c/script>'+c);var d="<!DOCTYPE html><html><head><script>var inDapIF=true;\x3c/script>"+c+"</head><body>"+b+"</body></html>";if(ej)a.srcdoc=d;else if(fj){var e=a.contentWindow.document;e.open("text/html","replace");e.write(d);e.close()}else gj(a,d)},ej=Ri&&"srcdoc"in document.createElement("iframe"),fj=Pi||Ri||Li&&Zi(11),gj=function(a,b){Li&&Zi(7)&&!Zi(10)&&6>hj()&&ij(b)&&(b=jj(b));var c=function(){a.contentWindow.goog_content=
b;a.contentWindow.location.replace("javascript:window.goog_content")};Li&&!dj(a)?kj(a,c):c()},hj=function(){var a=navigator.userAgent.match(/Trident\/([0-9]+.[0-9]+)/);return a?parseFloat(a[1]):0},dj=function(a){try{var b;var c=a.contentWindow;try{var d;if(d=!!c&&null!=c.location.href)b:{try{Hi(c.foo);d=!0;break b}catch(e){}d=!1}b=d}catch(e){b=!1}return b}catch(e){return!1}},lj=0,kj=function(a,b){var c="goog_rendering_callback"+lj++;Kb[c]=b;a.src="javascript:'<script>(function() {document.domain = \""+
document.domain+'";var continuation = window.parent.'+c+";window.parent."+c+" = null;continuation();})()\x3c/script>'"},ij=function(a){for(var b=0;b<a.length;++b)if(127<a.charCodeAt(b))return!0;return!1},jj=function(a){for(var b=unescape(encodeURIComponent(a)),c=Math.floor(b.length/2),d=[],e=0;e<c;++e)d[e]=String.fromCharCode(256*b.charCodeAt(2*e+1)+b.charCodeAt(2*e));1==b.length%2&&(d[c]=b.charAt(b.length-1));return d.join("")};/*
 Copyright (c) 2014 Derek Brans, MIT license https://github.com/krux/postscribe/blob/master/LICENSE. Portions derived from simplehtmlparser, which is licensed under the Apache License, Version 2.0 */

var nj=function(a,b,c,d){return function(){try{if(0<b.length){var e=b.shift(),f=nj(a,b,c,d);if("SCRIPT"==String(e.nodeName).toUpperCase()&&"text/gtmscript"==e.type){var g=P.createElement("script");g.async=!1;g.type="text/javascript";g.id=e.id;g.text=e.text||e.textContent||e.innerHTML||"";e.charset&&(g.charset=e.charset);var h=e.getAttribute("data-gtmsrc");h&&(g.src=h,ub(g,f));a.insertBefore(g,null);h||f()}else if(e.innerHTML&&0<=e.innerHTML.toLowerCase().indexOf("<script")){for(var k=[];e.firstChild;)k.push(e.removeChild(e.firstChild));
a.insertBefore(e,null);nj(e,k,f,d)()}else a.insertBefore(e,null),f()}else c()}catch(l){w(d)}}};var pj=function(a,b,c){if(P.body){var d=
a[Jd];d instanceof yb&&(d=d.resolve(zb(b,c)),b=Ab);if(a[Gf])try{Cb(sa(),"<script>var google_tag_manager=parent.google_tag_manager;\x3c/script>"+d),w(b)}catch(e){w(c)}else a[If]?oj(d,b,c):nj(P.body,Db(d),b,c)()}else C.setTimeout(function(){pj(a,b,c)},200)},_html=pj;_html.a="html";_html.b=["customScripts"];
var Bj=function(a,b,c,d,e){var f=a+"{"+(b+": "+c+(d?" !important":""))+"}";e&&(f=e+"{"+f+"}");var g=document;if(g.createStyleSheet){var h=yj(g),k=h.rules.length;h.insertRule(f,k);return function(){h.deleteRule?h.deleteRule(k):h.removeRule(k);h.insertRule("x {}",k)}}var l=zj(f,g);Aj(l,g);var m=l.parentNode;return function(){m.removeChild(l)}},Cj=null,yj=function(a){if(Cj)return Cj;for(var b=a.styleSheets.length-1;0<=b;b--){var c=a.styleSheets[b],d=c.ownerNode;if(d&&d.parentNode&&"HEAD"==d.parentNode.tagName)return Cj=
c}0==a.styleSheets.length&&a.createStyleSheet();return Cj=a.styleSheets[0]},zj=function(a,b){var c=(b||document).createElement("style");void 0!==c.cssText?c.cssText=a:c.innerHTML=a;return c},Aj=function(a,b){var c=b||document,d=c.getElementsByTagName("head")[0];d||(d=c.createElement("head"),c.body.parentNode.insertBefore(d,c.body));d.appendChild(a)};var Jj={},Kj=void 0,Lj=function(a){var b=Jj[a];b||(b={id:a,w:[],ma:0,ob:null,$a:void 0,fb:!1},Jj[a]=b);Kj=b},Nj=function(a,b,c,d){var e=Kj;if(!nh||!e)return!1;var f={id:e.id+":"+e.w.length,bc:b,ea:[],Xb:c,K:a,Va:0,La:d||null,yb:0,la:!1};e.w.push(f);null===a?(f.la=!0,b(null)):Mj(e);return!0},Oj=function(a){var b=Bj(a,"visibility","hidden",!0);return function(){ta(b)&&b.apply();b=null}},Pj=function(a,b,c,d){var e=b;if(!wb){var f=Oj(a.B);xb.push(f);e=function(a,c){var d=b(a,c);f();return d}}return Nj(a,
e,c,d)},Mj=function(a){if(!a.fb){for(var b=a.ma;b<a.w.length;b++){var c=a.w[b],d=b==a.ma;if(!c.la&&!Qj(d,c))break;c.la&&d&&a.ma++}a.w.length>a.ma?(a.ob||(a.ob=C.setTimeout(function(){a.ob=null;Mj(a)},80)),wb||a.$a||(a.$a=function(){w(function(){Mj(a)})},R(P,"DOMContentLoaded",a.$a))):Rj(a)}},Rj=function(a){for(var b=0;b<a.w.length;b++){var c=a.w[b];if(c.K)for(var d=ea(c.K.B)||[],e=0;e<d.length;e++){var f=d[e];f.gtmProgressiveApplied&&f.gtmProgressiveApplied[c.id]||(Sj(f,c.id),c.ea.push(Tj(f,c.id)))}}},
Qj=function(a,b){var c=[];if(b.K){var d=Uj(b.K,b.id),e=null;b.La&&(e=Uj(b.La,b.id+"-t"));for(var f=0;f<d.length;f++){var g=d[f],h;if(null!=e&&(h=e.length>f?e[f]:null,!h&&!wb&&(null===b.La.u||b.yb+c.length<b.La.u)))break;c.push({element:g,bd:h})}}if(!wb&&b.Xb&&(!a||null==b.K.u||b.K.u!=b.Va+c.length))return!1;for(var k=0;k<c.length;k++){var l=c[k].element,m=c[k].bd,n;b.Va++;Sj(l,b.id);m&&(b.yb++,n=b.id+"-t",Sj(m,n));var p=b.bc(l,m);ta(p)&&b.ea.push(p);b.ea.push(Tj(l,b.id));m&&n&&b.ea.push(Tj(m,n))}if(b.K.u&&
b.K.u==b.Va||wb)b.la=!0;return!0},Sj=function(a,b){a.gtmProgressiveApplied||(a.gtmProgressiveApplied={});a.gtmProgressiveApplied[b]=!0},Tj=function(a,b){return function(){a.gtmProgressiveApplied&&delete a.gtmProgressiveApplied[b]}},Uj=function(a,b){for(var c=ea(a.B)||[],d=[],e=0;e<c.length;e++){var f=c[e];if(!f.gtmProgressiveApplied||!f.gtmProgressiveApplied[b]){if(a.I&&!Vj(f))break;d.push(f)}}return d},Vj=function(a){if(wb)return!0;for(;a;){if(a.nextSibling)return!0;a=a.parentNode}return!1};var Oa=function(a,b){var c=b||Kb,d=c.onerror,e=!1;Ri&&!Zi("535.3")&&(e=!e);c.onerror=function(b,c,h,k,l){d&&d(b,c,h,k,l);a({message:b,fileName:c,line:h,lineNumber:h,vd:k,error:l});return e}};
var qk=function(a){var b=function(b){b=b||C.event;var c=a.call(this,b);b.returnValue=!1!==c&&(b.returnValue||void 0===b.returnValue);return c};b.gtmOnclickWrapper=!0;return b},_lcl=function(a,b){var c=Ha(a,Of,!0),d=Ha(a,yc,!0),e=W(a[Pf]);0>=e&&(e=2E3);var f=Ha(a,Bf,"");Aa("LINK_CLICK",!!c,!!d,e,String(f));if(!P.gtmLinkClickListener&&(P.gtmLinkClickListener=!0,!P.addEventListener)){var g=function(a){a=a||C.event;for(var b=ib(a);b;)b.onclick&&!b.onclick.gtmOnclickWrapper&&(b.onclick=qk(b.onclick)),
b=b.parentElement};R(P,"mousedown",g,!1);R(P,"keydown",function(a){a=a||C.event;13==a.keyCode&&g(a)},!1)}w(b)};_lcl.a="lcl";_lcl.b=[];var rk=function(a){if(!a)return!1;if(a[cc]&&Xa(a[ec])){for(var b=a[ec],c=0;c<b.length;c++)if(a[ec]=b[c],Vf(a))return!0;return!1}return Vf(a)};var Nk=86,Ok=[],Pk=[],Pg=[],Qk=new Uf,Rk=[],Sk=[],eh=[],fh=[],Tk=function(){this.S=[]};Tk.prototype.set=function(a,b){this.S.push([a,b]);return this};Tk.prototype.resolve=function(a,b){for(var c={},d=0;d<this.S.length;d++){var e=Sg(this.S[d][0],a,b),f=Sg(this.S[d][1],a,b);c[e]=f}return c};var Uk=function(a){this.index=a};Uk.prototype.resolve=function(a,b){var c=Pg[this.index];if(c&&!b(c)){var d=c[Wa];if(a){if(a.get(d))return;a.set(d,!0)}c=Sg(c,a,b);a&&a.set(d,!1);return Vf(c)}};
var _M=function(a){return new Uk(a)},Vk=function(a){this.resolve=function(b,c){for(var d=[],e=!1,f=0;f<a.length;f++){var g=Sg(Ok[a[f]],b,c);g===lb&&(e=!0);d.push(g)}return e?new yb(d):d.join("")}},_T=function(a){return new Vk(arguments)},Wk=function(a){function b(b){for(var c=1;c<a.length;c++)if(a[c]==b)return!0;return!1}this.resolve=
function(c,d){var e=Sg(a[0],c,d);if(a[0]instanceof Uk&&b(8)&&b(16)){if(e===lb)return e;var f=Fa();Qk.set(f,e);return'google_tag_manager["'+Ca.f+"\"].macro('"+f+"')"}e=String(e);for(var g=1;g<a.length;g++)e=sk[a[g]](e);return e}},_E=function(a,b){return new Wk(arguments)},Xk=function(a,b){this.A=a;this.ua=b},_R=function(a,b){return new Xk(a,b)};
var Sg=function(a,b,c){var d=a;if(a instanceof Uk||a instanceof Tk||a instanceof Vk||a instanceof Wk)return a.resolve(b,c);if(!(a instanceof Xk))if(Xa(a)){d=[];for(var e=0;e<a.length;e++)d[e]=Sg(a[e],b,c)}else if(a&&"object"==typeof a){d={};for(var f in a)a.hasOwnProperty(f)&&(d[f]=Sg(a[f],b,c))}return d},$k=function(){for(var a=[_eq,_e,'_event',_M(0),'gtm.js','1706105_2147479553',_ua,true,__c,'GA ID','1','UA-4793285-1',_M(1),false,'\x26tid',{14:12},1,_cn,_j,'Title Tag','document.title',_M(2),'Page Not Found','1706105_8','404 Page',_u,'Page URL',_M(3),'\x26t','\x26ec','\x26ea','\x26ni','event',{14:12,28:32,29:24,30:27,31:7},7,'.*','1706105_12',_lcl,'1706105_11','2000',8,_html,'\n\x3cscript type\x3d\x22text/gtmscript\x22\x3e(function(a,c,e,f,d,b){a.hj\x3da.hj||function(){(a.hj.q\x3da.hj.q||[]).push(arguments)};a._hjSettings\x3d{hjid:279741,hjsv:5};d\x3dc.getElementsByTagName(\x22head\x22)[0];b\x3dc.createElement(\x22script\x22);b.async\x3d1;b.src\x3de+a._hjSettings.hjid+f+a._hjSettings.hjsv;d.appendChild(b)})(window,document,\x22//static.hotjar.com/c/hotjar-\x22,\x22.js?sv\\x3d\x22);\x3c/script\x3e',2,_v,'Element ID','gtm.elementId',_eu,'Element URL','Hostname','skynews.com.au','Page Hostname','host','Page Path','path',_f,'Referrer','Event','Click Element','gtm.element','Click Classes','gtm.elementClasses','Click ID','Click Target','gtm.elementTarget','Click URL','gtm.elementUrl',_et,'Click Text','Form Element','Form Classes','Form ID','Form Target','Form URL','Form Text','Error Message','gtm.errorMessage','Error URL','gtm.errorUrl','Error Line','gtm.errorLineNumber',_dbg,'Debug Mode'],b=[],c=0;c<a.length;c++)b[c]=
Zk(c,a);return b},Zk=function(a,b){var c=b[a],d=c;if(c instanceof Uk||c instanceof Wk||c instanceof Vk||c instanceof Xk)d=c;else if(Xa(c)){d=[];for(var e=0;e<c.length;e++)d[e]=Zk(c[e],b)}else if("object"==typeof c){d=new Tk;for(var f in c)c.hasOwnProperty(f)&&d.set(b[f],Zk(c[f],b))}return d},bl=function(a,b){for(var c=b?b.split(","):[],d=0;d<c.length;d++){var e=c[d]=c[d].split(":");0==a&&(e[1]=
Ok[e[1]]);if(1==a){var f=al(e[0]);e=c[d]={};for(var g=0;g<f.length;g++){var h=Pk[f[g]];e[h[0]]=h[1]}}if(2==a)for(g=0;4>g;g++)e[g]=al(e[g]);3==a&&(c[d]=Ok[e[0]]);if(4==a)for(g=0;2>g;g++)if(e[g]){e[g]=e[g].split(".");for(var k=0;k<e[g].length;k++)e[g][k]=Ok[e[g][k]]}else e[g]=[];5==a&&(c[d]=e[0])}return c},al=function(a){var b=[];if(!a)return b;for(var c=0,d=0;d<a.length&&c<Nk;c+=6,d++){var e=a&&a.charCodeAt(d)||65;if(65!=e){var f;f=65<e&&90>=e?e-65:97<=e&&122>=e?e-97+26:95==e?63:48<=e?e-48+52:62;1&
f&&b.push(c);2&f&&b.push(c+1);4&f&&b.push(c+2);8&f&&b.push(c+3);16&f&&b.push(c+4);32&f&&b.push(c+5)}}return b},cl=function(a,b,c){a.push.apply(a,bl(b,c))};var dl;
var Rg=function(a,b){if(null===a||void 0===a)return a;if(b.propertyRenamingRequired){var c={},d;for(d in a)if(a.hasOwnProperty(d)){var e=gl[d];e&&0==e.indexOf("vtp_")&&(c[e]=a[d])}c.__metadata=b;return c}return a},jl=function(a){},kl=function(a,b){},Ug=function(a){};var ll,ml;var xl=function(a){return function(){}},yl=function(a){return function(){}};var zl=function(a){var b=this;this.i=a;this.ja=this.Qb=!1;this.Ka=[];this.Ga=[];this.ba=function(){b.ja||Zf(b.Ka);fg(b,1);if(Sb[a])for(var c=0;c<Sb[a].length;c++)Sb[a].shift().ba()};this.aa=function(){b.ja||Zf(b.Ga);fg(b,2);if(Sb[a])for(var c=0;c<Sb[a].length;c++)Sb[a].shift().aa()};this.D=Ab},Al=function(a,b){a.Ka.push(b)},Bl=function(a,b){a.Ga.push(b)},Cl=function(a){this.M=[];this.lb=[];this.Bb={};this.Ib=[];this.Z=0;this.jb={};this.nb={};this.mb={};this.event=a};Cl.prototype.addListener=function(a){this.Ib.push(a)};
var Dl=function(a){0<a.Z||Zf(a.Ib)},El=function(a,b,c,d,e,f){if(!c.ja){a.M[b]=c;void 0==d&&(d=[]);void 0==e&&(e=[]);void 0==f&&(f=[]);d=Xa(d)?d.slice():["or",d];e=Xa(e)?e.slice():[e];f=Xa(f)?f.slice():[f];a.Bb[b]=d;a.jb[b]=0<e.length;a.nb[b]=0<f.length;a.Z++;var g=function(){0<a.Z&&!a.jb[b]&&!a.nb[b]&&a.Z--;Dl(a)};Al(c,g);Bl(c,g)}},Jl=function(a){for(var b=[],c={},d=0;d<a.M.length;c={U:c.U},d++)if(c.U=a.M[d],c.U){var e=a.Bb[d],f=a.jb[d],g=a.nb[d];if(0!=e.length||f||g){if(0<e.length)for(var h=Fl(e,
c.U.D),k=0;k<e.length;k++)e[k]instanceof Xk&&e[k].A!=d&&Gl(a,e[k].A,h);(f||g)&&Hl(a,d,function(a){return function(){0<a.U.C.Z&&a.U.C.Z--;Dl(a.U.C)}}(c))}else b.push(d)}for(d=0;d<b.length;d++)a.M[b[d]].D();for(d=0;d<a.lb.length;d++){var l=a.lb[d];Il(l);0<l.length&&l[0].D()}},Gl=function(a,b,c){a.M[b]&&(Al(a.M[b],function(){c(b,!0)}),Bl(a.M[b],function(){c(b,!1)}))},Fl=function(a,b){var c=Ab,d=!1;return function(e,f){var g;a:{for(var h=0;h<a.length;h++)if(a[h]instanceof Xk&&a[h].A===e||a[h]===e){g=
h;break a}g=-1}d||0>g||("or"==a[0]?f?(d=!0,b()):(a.splice(g,1),1==a.length&&(d=!0,c())):f?(a.splice(g,1),1==a.length&&(d=!0,b())):(d=!0,c()))}},Hl=function(a,b,c){var d=[],e=!1,f=function(b){var c,g,h=Sk[b];if(a.event.g(h)){}else g=Kl(h,b,a.event.g,a);if(c=g){var k=Ll(b,!0);0<k.length&&f(k[0].A);d.push(c);var l=Ll(b,!1);0<l.length&&f(l[0].A)}else e=
!0};f(b);if(!e){for(var g=0;g<d.length;g++){var h=d[g],k=Ll(h.i,!0);if(0<k.length){var l=d[g-1],m=Ml(h);Al(l,m);0==k[0].ua?Bl(l,m):Bl(l,c)}var n=Ll(h.i,!1);0<n.length&&(m=Ml(d[g+1]),Al(h,m),0==n[0].ua?Bl(h,m):Bl(h,c))}Al(d[d.length-1],c);Bl(d[d.length-1],c);a.lb.push(d)}},Ll=function(a,b){var c=b?Te:kf,d=Sk[a],e=void 0===d[c]?[]:d[c];return Xa(e)?e:[e]},Ml=function(a){return function(){a.D()}},Il=function(a){for(var b=[],c=0;c<a.length;c++){var d=a[c],e=d.i,f=Rb[e],g=f.firingOption;if(0!=g&&(1==g&&
void 0!==d.C.mb[e]||2==g&&void 0!==f.state)&&(b.push(d),2==f.state&&c!=a.length-1)){var h=Ll(a[c+1].i,!0);if(0<h.length&&1==h[0].ua)for(++c;c<a.length;c++)b.push(a[c])}}var k=Nl(b),l;for(l in k)if(k.hasOwnProperty(l)){for(var m=void 0,n=void 0,p=k[l],t=p[0],v=p[p.length-1],r,x=0;x<a.length;x++){var E=a[x];!m&&E.i==t&&0<x&&(m=a[x-1]);E.i==v&&x<a.length-1&&(n=a[x+1]);if(-1<Sf(p,E.i))if(r=a.splice(x,1)[0],E.i==v)break;else x--}if(r){var F=Number(l),y=m,I=n;if(y){var M=y.Ka[0],B=y.Ga[0],z=y;z.Ka=[];z.Ga=
[];Al(y,M);Bl(y,B)}if(y&&I){var D=Ml(I);Al(y,D);var G=Ll(y.i,!1);0<G.length&&G[0].A!=F&&0==G[0].ua&&Bl(y,D);var L=Ll(I.i,!0);0<L.length&&L[0].A!=F&&0==L[0].ua&&Bl(y,D)}}}},Nl=function(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=[],f=function(a){var b=Ll(a,!0);0<b.length&&f(b[0].A);e.push(a);var c=Ll(a,!1);0<c.length&&f(c[0].A)};f(d.i);b[d.i]=e}Ol(a,b);return b},Ol=function(a,b){for(var c=0;c<a.length;c++){var d=a[c].i,e;for(e in b)if(b.hasOwnProperty(e)&&e!=d&&-1<Sf(b[e],d)){delete b[d];break}}};var Pl=function(a,b,c){return function(){a[Fd]=b.ba;a[Gd]=b.aa;var d=b.i,e=b.C&&b.C.mb[d],f=Rb[d]&&Rb[d].state,g=e?void 0!==e:b.Qb||b.ja,h=Rb[d]&&Rb[d].firingOption,k=h&&2==h,l=h&&1==h;if(!g&&void 0===f||!g&&!k||!k&&!l){fg(b,0);var m=b.C?b.C.event:void 0,n=a;n=Sg(n,new Uf,c);a=n;if(m){}Vf(a,b.ba,b.aa)}else k&&0==f||l&&0==e?Sb[d].push(b):k&&1==f||l&&1==e?b.ba():b.aa()}},Kl=function(a,b,c,d){var e=d&&d.M,f;if(f=e)a:{if(e&&Xa(e)&&0!=e.length)for(var g=0;g<e.length;g++)if(e[g]&&e[g].i===b){f=e[g];break a}f=void 0}var h=f||new zl(b);h.C=d;Al(h,xl(a));Bl(h,yl(a));h.D=Pl(a,h,c);return h};
var Tl=!1,_ua=function(a,b,c){function d(a){var b=[].slice.call(arguments,0);b[0]=n+b[0];C[l()].apply(window,b)}function e(b,c){void 0!==a[c]&&d("set",b,a[c])}function f(a,b){return void 0===b?b:a(b)}function g(a,b){if(b)for(var c in b)b.hasOwnProperty(c)&&d("set",a+c,b[c])}function h(){var b=function(a,b,c){if(!Ga(b))return!1;for(var e=Ha(Object(b),c,[]),f=0;e&&f<e.length;f++)d(a,e[f]);return!!e&&0<e.length},c;a[jd]?c=Y("ecommerce"):
a[id]&&(c=a[id].ecommerce);if(!Ga(c))return;c=Object(c);var e=Ha(a[Bd],"currencyCode",c.currencyCode);void 0!==e&&d("set","&cu",e);b("ec:addImpression",c,"impressions");if(b("ec:addPromo",c[c.promoClick?"promoClick":"promoView"],"promotions")&&c.promoClick){d("ec:setAction","promo_click",c.promoClick.actionField);return}for(var f="detail checkout checkout_option click add remove purchase refund".split(" "),g=0;g<f.length;g++){var h=c[f[g]];if(h){b("ec:addProduct",h,"products");d("ec:setAction",f[g],
h.actionField);break}}}function k(a,b,c){var d=0;if(void 0!==a)for(var e in a)if(a.hasOwnProperty(e)&&(c&&v[e]||!c&&void 0===v[e])){var f=r[e]?Ia(a[e]):a[e];"anonymizeIp"!=e||f||(f=void 0);b[e]=f;d++}return d}Ra("GoogleAnalyticsObject",a[je]||"ga");var l=function(){return C.GoogleAnalyticsObject},m=Ra(l(),function(){var a=C[l()];a.q=a.q||[];a.q.push(arguments)});m.l=Number(K());var n="",p="";"string"!=typeof a[xf]?(p=Fa(),n=p+"."):""!==
a[xf]&&(p=a[xf],n=p+".");var t=!1;
var x={name:p};m("create",a[Ub],x);d("set","&gtm",pa(!0));e("nonInteraction",oe);var F;a[Zd]&&d("require","linkid","linkid.js");d("set","hitCallback",function(){if(ta(a[Hd]))a[Hd]();else{var c=a[Bd],d=c&&c.hitCallback;ta(d)&&d()}b()});if(a[tf]){a[qd]&&(d("require","ec","ec.js"),h());var y={hitType:"event",eventCategory:String(a[ud]),eventAction:String(a[td]),eventLabel:f(String,a[vd]),eventValue:f(W,a[wd])};k(F,y,!1);d("send",y);}else if(a[uf]){}else if(a[wf]){}else if(a[vf]){}else if(a[$c]){}else if(a[Yc]){}else if(a[sf]){}else{a[qd]&&(d("require","ec","ec.js"),h());if(a[hd]&&!a[sd]){var L="_dc_gtm_"+String(a[Ub]).replace(/[^A-Za-z0-9-]/g,"");d("require","displayfeatures",void 0,{cookieName:L})}F?d("send","pageview",F):d("send","pageview");}if(!Tl){var Q=a[Wc]?"u/analytics_debug.js":"analytics.js";a[Pd]&&!a[Wc]&&(Q="internal/"+Q);Tl=
!0;u(ka("https:","http:","//www.google-analytics.com/"+Q,t),function(){C[l()].loaded||c()},c)}};_ua.a="ua";_ua.b=["google"];var Wl=function(){var a=[];return function(b,c){if(void 0===a[b]){var d=Rk[b]&&Sg(Rk[b],new Uf,c),e=d;d&&(e=rk(d));a[b]=[e,d]}return a[b]}},Xl=function(a,b){for(var c=b[0],d=0;d<c.length;d++)if(!a.Y(c[d],a.g)[0])return!1;var e=b[2];for(d=0;d<e.length;d++)if(a.Y(e[d],a.g)[0])return!1;return!0},Yl=!1;
Jg=function(a,b,c,d,e){switch(b){case "gtm.js":if(Yl)return!1;Yl=!0;break;case "gtm.sync":if(Y("gtm.snippet")!=Ob)return!1}for(var f={id:a,name:b,Aa:d||Ab,ia:al(),Ja:al(),Y:Wl(),g:Og(c)},g=[],h=0;h<eh.length;h++)if(Xl(f,eh[h])){g[h]=!0;for(var k=f,l=eh[h],m=l[1],n=0;n<m.length;n++)k.ia[m[n]]=!0;var p=l[3];for(n=0;n<p.length;n++)k.Ja[p[n]]=!0}else g[h]=!1;var O=[];for(var N=0;N<Nk;N++)if(f.ia[N]&&!f.Ja[N])if(f.g(Sk[N])){}else{O[N]=
Sk[N];}f.ra=O;for(var ha=new Cl(f),V=0;V<Nk;V++)if(f.ia[V]&&!f.Ja[V])if(f.g(Sk[V])){}else{var Ja=f.ra[V],Xj=Kl(Ja,V,f.g,ha);El(ha,V,Xj,Ja[cd],Ja[Te],Ja[kf]);if(Ja[Tb])break}ha.addListener(f.Aa);Jl(ha);Dl(ha);e&&ta(e)&&e({passingRules:g,resolvedTags:f.ra});
if("gtm.js"==b||"gtm.sync"==b)a:{}for(var cg in f.ra)if(f.ra.hasOwnProperty(cg)){var dg=f.ra[cg];if(void 0==dg[Wa]||!gg(dg[Wa],"_implicit"))return!0}return!1};var $l=function(){};var am=function(){};var Zl={macro:function(a){if(Qk.contains(a))return Qk.get(a)}};Zl.dataLayer=xg;Zl.onHtmlSuccess=Ai(!0);Zl.onHtmlFailure=Ai(!1);Zl.callback=function(a){Ta.hasOwnProperty(a)&&ta(Ta[a])&&Ta[a]();delete Ta[a]};
Zl.jc=function(){var a=C.google_tag_manager;a||(a=C.google_tag_manager={});qb=a;if(a[Ca.f]){var b=qb.zones;b&&b.registerNatural(Ca.f)}else{a[Ca.f]=Zl;Hh();gh();Ok.push.apply(Ok,$k());cl(Pk,0,"14:0,14:1,16:2,3:3,4:4,14:6,20:7,14:8,16:9,25:10,26:11,0:12,11:13,10:13,24:13,7:13,8:13,1:15,17:13,9:13,21:16,14:17,14:18,16:19,18:20,3:21,4:22,22:7,2:7,13:24,14:25,16:26,12:27,19:7,1:33,21:34,3:27,4:35,14:37,27:7,5:7,23:38,28:39,21:40,14:41,15:42,21:43,14:44,16:45,18:46,14:47,16:48,16:49,26:50,16:51,6:52,16:53,6:54,14:55,16:56,16:57,16:58,18:59,16:60,18:61,16:62,16:63,18:64,16:65,18:66,14:67,16:68,16:69,16:70,16:71,16:72,16:73,16:74,16:75,18:76,16:77,18:78,16:79,18:80,14:81,16:82");cl(Pg,1,"G,Ae,AAAwB,AAAAAD,AAAAAAAgD,AAAAAAAAM,AKAAAAAAw,AAAAABAAAD,AAAAABAAAM,AAAAAAAAAw,CAAAAAAAAAB,AAAAAAAgAAG,AAAAAAAgAAY,AAAAAAAgCAg,AAAAAAAgAAAD,AAAAAAAgAAAM,AAAAAAAAAAAw,AAAAAAAgAAEAB,AAAAAAAgAAQAC,AAAAAAAgCAAAE,AAAAAAAgAAACI,AAAAAAAgAAAIQ,AAAAAAAAAAAQg,AAAAAAAgAAAAAD,AAAAAAAgAAAAAM,AAAAAAAgAAAAAw,AAAAAAAAAAAAAAD");cl(Rk,1,"Z,AAAIG,AAAIAAD");cl(Sk,1,"gh_H,ghLD48,AAAAAA8D,ABAAAAAc");cl(eh,2,"B:J::,D:C::,F:E::");cl(fh,4,"5.5:,23:,36:");for(var c=0;c<Sk.length;c++){var d=Sk[c],e=1;d[qe]?e=2:
d[Cf]&&(e=0);Rb[c]={firingOption:e,state:void 0};Sb[c]=[]}Fg();Xg();var n=C;if("interactive"==P.readyState&&!P.createEventObject||"complete"==P.readyState)lg();else{R(P,"DOMContentLoaded",lg);R(P,"readystatechange",lg);if(P.createEventObject&&P.documentElement.doScroll){var p=!0;try{p=!n.frameElement}catch(E){}p&&ng()}R(n,"load",lg)}"complete"===P.readyState?qg():R(C,"load",qg);am();$l();a:{}}};Zl.jc();var _vs="res_ts:1477541572557000,srv_cl:172802918,ds:live,cv:8";
})()
